### ISSUE TITLE
Lỗi - Thông báo phát sinh chi phí thanh toán

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#101]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/02/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_chauthanh_bt_01`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018003546` - _**MaKB**_: `2302009248` - _**NgayKCB**_: `22/02/2023` - _**MaPhong**_: `07` - _**MaDV**_: `02` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH183`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân chỉ định cls không thanh toán bhyt mã: CH183 và check miễn giảm 100%
Khi in bảng kê 01 6556 Printer vẫn cảnh báo phát sinh chi phí thanh toán!

```
cảnh báo printer
![image](https://user-images.githubusercontent.com/96155021/220555648-648640f4-7a3b-4c67-91eb-5818fd13cb30.png)

![image](https://user-images.githubusercontent.com/96155021/220555848-910c24f6-1823-43ba-a95e-32ce7abe0467.png)

**Comment by ongtrieuhau** [comment]
Cho anh xin lại dữ liệu nhé @le-an-87

**Comment by le-an-87** [comment]
Chổ này bị mất dữ liệu rồi để có trường hợp khác em báo lại nhe anh!
