### ISSUE TITLE
Lỗi - Sai đơn vị tuổi.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#102]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV NHi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_022023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023031380` - _**MaKB**_: `2302042988` - _**MaBA**_: `2023005702` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `TH6.TMN.0303.084239` - _**NgayHD**_: `03/03/2023` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Đối với những toa thuốc được chỉ định từ **nội trú**, đơn vị tuổi là tháng thì phần mềm đang hiển thị sai thành đơn vị là ngày.
psdangky.dvtuoi -> 1: tuổi, 2: tháng, 3: ngày
Trường hợp như hình là psdangky.dvtuoi=2 nhưng form hiển thị đơn vị tuổi là ngày.
![image](https://user-images.githubusercontent.com/99630883/222614207-9a6aa8f2-ec19-4eb1-89c9-7b330bef4796.png)

**Comment by ongtrieuhau** [comment]
Phần này là sử dụng dll của a @vuongdh , nhờ a @vuongdh check lại giúp em

**Comment by vuongdh** [comment]
@lqbinh1987 em coi cột ngày dtvtuoi là gì vậy? --> lấy dữ liệu từ đó

**Comment by lqbinh1987** [comment]
anh @ongtrieuhau ơi cập nhật printer dùm em, a Vương đã fix xong.
![image](https://user-images.githubusercontent.com/99630883/228749041-9ce09e10-653a-4fb7-bb69-65e2c7693906.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0405.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/3e8402b1dd4555ad697382f6e311f63e72d4c81d)
