### ISSUE TITLE
Yêu cầu - BV Trà Cú

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#104]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Trà Cú**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BV Đề nghị hỗ trợ quét mã mạch bệnh nhân thực hiện các chức năng sau:

1. Module Fees: khi quét mã bệnh nhân phần mềm tự lập phiếu thu chi phí của bệnh nhân đó.

2. Module Printer: quét mã bệnh nhân phần mềm in bảng kê của bệnh nhân.

3. Module Laboratory: quét mã bệnh nhân phần mềm thực hiện lấy mẫu và in Templace để dán vào các ống nghiệm.

```

**Comment by nghivanbi** [comment]
@ongtrieuhau  ghi nhận mấy cái này, khi qua bệnh viện check lại cụ thể cái nha. Thứ 2 tuần tới báo cáo lại.

**Comment by vinh-dh** [comment]
@le-an-87 chức năng in tem mã vạch ống nghiệm là do phần mềm LIS làm. Chứ Labo mình không có làm được cái đó nhe.

**Comment by le-an-87** [comment]
01/04/2023!

**Comment by ongtrieuhau** [comment]
Cái này Fees và Printer đều có hỗ trợ hết rồi nhé.

- **Fees** `vpsudungmavach`
- **Printer**: `chờ duyệt nhé`

**Comment by vinh-dh** [comment]
`3. Module Laboratory: quét mã bệnh nhân phần mềm thực hiện lấy mẫu và in Templace để dán vào các ống nghiệm.`

- Quét mã BN thực hiện lấy mẫu là không thể thực hiện ==> Danh sách bệnh nhân đang thể hiện theo thời điểm chỉ định (1 BN có nhiều thời điểm sẽ có nhiều dòng, quét rồi lấy mẫu dòng nào?)
- In Templace khi lấy mẫu hiện tại đang có tham số: `xn.inphieuxn`, vào thư mục cài đặt Labo điều chỉnh (nếu có) file template.doc.

**Comment by le-an-87** [comment]
issues này có thực hiện cho bv không hé anh @nghivanbi, nếu không em đóng lại nhe!

**Comment by nghivanbi** [comment]
hỗ trợ Fees và Printer nhé @ongtrieuhau, @le-an-87,  Laboratory hiển thị thêm cột MaBn chỗ danh sách nha @vinh-dh chô bệnh viện có thể tìm theo mabn khi cần.

**Comment by vinh-dh** [comment]
- [HospitalLaboratorySetup20230516](https://gofile.me/78TQg/e9UdcdBtQ)

**Comment by le-an-87** [comment]
Labor đã bổ sung "Laboratory hiển thị thêm cột MaBn chỗ danh sách nha @vinh-dh chô bệnh viện có thể tìm theo mabn khi cần."
Form trả kết quả xét nghiệm và Khám sức khỏe hợp đồng!
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/408c184b-111b-4391-ad30-fc65a97f0160)

* khi chạy lên hiển thị 2 thông báo như hình. Mình tắt thông báo này được không anh @vinh-dh 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/a1f4de17-7a27-4b8c-b094-9949c6fe6fb5)

**Comment by vinh-dh** [comment]
Thử lại nhé @le-an-87 
- [HospitalLaboratorySetup20230516v1](https://gofile.me/78TQg/AQgEn459x)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.4](https://github.com/dh-hos/dhg.hospitalprinter/commit/576856f9d598234faa1067872bfe1496daed2591)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Đã gửi cho bv sử dụng!
