### ISSUE TITLE
Yêu cầu - Bổ sung chức năng lập phiếu thu hàng loạt.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#106]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **01/042023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV NHi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_022023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Như đã trao đổi với anh Hậu, và anh Hậu cũng đồng ý bổ sung chức năng theo đề nghị sau.
=> Đề nghị bổ sung thêm chức năng có thể check chọn đồng loạt nhiều toa thuốc để lập phiếu thu(BV đang cấu hình chức năng lập hóa đơn điện tử khi Lưu phiếu thu).

![image](https://user-images.githubusercontent.com/99630883/230539476-4c2df04f-51b0-441c-aa49-170f60144c2f.png)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau với anh @nghivanbi xem xét yêu cầu này dùm em, như hổm em thảo luận với a Hậu á.

**Comment by lqbinh1987** [comment]
Khi làm theo hướng cho chọn nhiều chứng từ thì em đề xuất bắt thêm: Ví dụ nếu máy A đang chọn danh sách những chứng từ rồi, thì máy B không được chọn những chứng từ mà máy A đã chọn tránh trường hợp 2 máy cùng chọn trùng những chứng từ đó, sẽ xảy ra trường hợp 1 chứng từ mà đươc lưu phiếu thu 2 lần chỉ chênh lệch 1-2s do không cập nhật được trạng thái đã thu của chứng từ thuốc đó, 2 số chứng từ phiếu thu khác nhau và sẽ có 2 mã bí mật khác nhau -> 2 hddt trùng nhau.
Anh @ongtrieuhau , anh @nghivanbi .

**Comment by nghivanbi** [comment]
@ongtrieuhau hỗ trợ nhé

**Comment by lqbinh1987** [comment]
Nhờ anh @ongtrieuhau tranh thủ phần này dùm e.

**Comment by ongtrieuhau** [comment]
Đang thực hiện nhé

**Comment by ongtrieuhau** [comment]
Dữ liệu này anh test hóa đơn điện tử được hông @lqbinh1987

**Comment by lqbinh1987** [comment]
Được nhe anh @ongtrieuhau

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.23.0626.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/7277e70aba51d990ce8bdc12be61c11ac6d820ea)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau, bắt phiếu thu đang lập hddt thì ok rồi anh, nhưng vấn đề nó đang nằm ở chổ đang lưu phiếu thu á, 2 máy mà cũng bấm nút Lưu phiếu thu, thì dữ liệu nó sẽ lưu ra 2 phiếu thu luôn á, có 2 mã tra cứu khác nhau, tại thời điểm sau khi lưu xong thì 2 máy load 2 số chứng từ khác nhau luôn => 2 máy tự lập thành 2 hddt luôn.

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/3ea46a20-b34c-42a9-b200-1b2f77c0f262)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/cadae081-1c6f-4118-8c32-337a245a32ad)

**Comment by ongtrieuhau** [comment]
Ok, để bắt thêm trường hợp này luôn

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0628.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/428ec0df739ea49e83feb864927cdb7b1cd044a4)
