### ISSUE TITLE
Lỗi - chức năng in bệnh nhân không lấy thuốc set lại ngày uống bệnh nhân = 0 (dmthebhyt.songay)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#109]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **20/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `96133`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK HỒNG ĐỨC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_pkhd_loi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018052046` - _**MaKB**_: `2304001387` - _**NgayKCB**_: `03/04/2023` - _**MaPhong**_: `07` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có 2 toa thuốc
- Toa BH: 127.00224/202304 - số ngày uống = 20
- Toa TP: 127.00225/202304 - số ngày uống = 20
- > printer TP in toa thuốc chọn in không lấy thuốc thì printer set dmthebhyt.songay = 0
  => Dẫn đến khi đăng ký khám bệnh thì Register không kiểm tra được ngày hết hạn toa thuốc của bệnh nhân -> không cảnh báo
```
alo anh @nghivanbi ơi!
Coi thống nhất lại trường hợp này với printer hé anh!
Bệnh viện muốn cảnh báo theo ngày toa thuốc in thanh toán là 20 ngày

**Comment by ongtrieuhau** [comment]
Dữ liệu luôn nhé @le-an-87
