### ISSUE TITLE
Lỗi - Sai trạng thái đã in bệnh nhân không lấy thuốc toa mua ngoài

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#111]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51219`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Minh Quang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_minhquang_rep_thieuxml`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000001` - _**MaKB**_: `2303000001` - _**MaBA**_: `MaBA` _**NgayKCB**_: `26/04/2023` - _**MaPhong**_: `KB6` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân BHYT có toa BHYT và toa mua ngoài
```
1. Printer kho BHYT in toa thuốc, bảng kê BHYT xong  qua kho nhà thuốc in bệnh nhân không lấy thuốc toa mua ngoài thì phần mềm Printer set lại trạng thái đã in bị sai khambenh.dain = 3, chidinhcls.dain = 3 (không xuất được XML4210)
2. Printer kho nhà thuốc: chức năng Mở khoá chứng từ không lấy được thông in bệnh nhân mở khoá toa mua ngoài để phục hồi toa
3. Printer kho nhà thuốc: In phiếu KCB -> Không lấy toa không lấy được danh sách bệnh nhân không lấy toa
```
1.
![ảnh](https://user-images.githubusercontent.com/97272332/234470735-9a9428cc-cd9f-4112-9831-9391e5117506.png)
![ảnh](https://user-images.githubusercontent.com/97272332/234470793-68a922df-2d1e-4b52-9c90-dffd966cba87.png)

2.
![ảnh](https://user-images.githubusercontent.com/97272332/234471016-6ae78eb1-5444-47cb-a6c7-73baed686128.png)

3.
![ảnh](https://user-images.githubusercontent.com/97272332/234471053-91d42466-49b5-4183-8fc5-517937c230ee.png)

**Comment by ongtrieuhau** [comment]
Nhờ @chauthanhtra  nhập một bệnh BHYT mới vừa có toa BHYT và vừa có Toa mua ngoài giúp anh nhé

**Comment by chauthanhtra** [comment]
Bệnh nhân mới nha anh
Ngày KCB: 12/9/2023
Mã BN: 2023000006
Mã KB: 2303000006

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.5](https://github.com/dh-hos/dhg.hospitalprinter/commit/9172c831b8bd4a1b4520ff36610e237b5faa0eb9)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
Alo anh
- Trường hợp toa mua ngoài kho thu phí bấm Không lấy toa và đồng ý in bảng kê BHYT thì cột đã in bằng 2 có thể phục hồi được, Admin và Reports đều xuất được XML => OK

- Trường hợp toa mua ngoài kho thu phí bấm Không lấy toa và không in bảng kê BHYT thì cột dain trên chidinhcls, khambenh, chungtu, pshdxn đều bằng 3 thì: (Do đây là toa mua ngoài và đã in bảng kê BH rồi nên PK không muốn in thêm bảng kê)
          + Printer -> Mở khóa chứng từ không tìm thấy bệnh nhân
          + Printer -> Không lấy toa không tìm thấy bệnh nhân để phục hồi toa (xem tất cả bệnh nhân thì thấy có bệnh nhân nhưng không phục hồi được do chưa mở khóa)
          + Reports -> xuất XML và các báo cáo Reports thì không xuất được bệnh nhân có đã in bằng 3 (chổ này anh với anh Vinh thống nhất lại trường hợp đã in bằng 3 nha)

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/165dd153-0110-4d49-b2e4-d205647d6872)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/4c4cc017-6a59-44fb-9d0c-c47224967467)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/ec7781f0-d585-43fa-9a66-0e63adb67d5f)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.7](https://github.com/dh-hos/dhg.hospitalprinter/commit/42c6cc5f4040a4a862cf0aab6526c6042b938a32)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>
