### ISSUE TITLE
Lỗi - HIỂN THỊ SAI THÔNG TIN ĐƠN VỊ TUỔI - BẢNG KÊ HOÁ ĐƠN NHÀ THUỐC

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprinter#112]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK SA ĐÉC**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_tpsadec_dvtuoi_bangkehdbanle`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Thông tin đơn vị tuổi hiển thị sai tại Bảng kê Hoá đơn nhà thuốc.
![image](https://user-images.githubusercontent.com/130281806/234740538-a58c5a4e-e77d-49c7-9ce3-09341efc395a.png)
![image](https://user-images.githubusercontent.com/130281806/234740551-4a7bb0d7-9127-4c8b-a12b-613fe80e1b3f.png)
![image](https://user-images.githubusercontent.com/130281806/234740566-38631167-7d4d-459b-9e11-adedce1b8cb3.png)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau coi tranh thủ chổ này dùm em, người dùng báo cáo Lãnh đạo bên đó đang phản ảnh phần mềm.

**Comment by ongtrieuhau** [comment]
Nhờ cung cấp lại database nhé, hiện tại hông thấy trên server nữa

**Comment by nqhoa1005** [comment]
em đã bổ sung lại dữ liệu
hoa_tpsadec_dvtuoi_bangkehdbanle
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/e01eee98-3d8f-4ef1-9bbc-e4360db8c892)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/ee01692c-8cdf-4054-bb07-457e9351acce)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0627.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/42a25c2c20b6affd60b4284b5a5d8c76d947f829)

**Comment by ongtrieuhau** [comment]
Cap nhat [3.23.0628.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/d3c15b84b4dd4a7f68f2b5357dfbf59ece2c54ab)

**Comment by nqhoa1005** [comment]
Chổ tuổi em test lại thấy thể hiện khác với trên form anh Hậu
ví dụ ca này trên form thể hiện 19 tháng nhưng trong bảng kê thể hiện 2 tuổi
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/55ed60fb-2a91-4994-be7f-684a78de6728)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/d9f5f5cb-6db4-41dc-b687-a44fa3fbe796)

- Ngoài ra chổ năm sinh trên form khi click vào mới tính lại đơn vị tuổi.

https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/acbafcef-2c92-423c-a0d7-8e55aa122bba

**Comment by lqbinh1987** [comment]
alo nhờ a Hậu  @ongtrieuhau  xem cái này dùm anh.

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau coi dùm em chổ này, BV đangin bảng kê hằng ngày mà nó sai đơn vị tuổi hết hà anh ơi. nó nhằn quá

**Comment by nqhoa1005** [comment]
@ongtrieuhau xem dùm em cái này, lâu quá nó hối nữa rồi anh ơi

**Comment by lqbinh1987** [comment]
@ongtrieuhau, anh coi chổ này dùm em. BV nó phàn nàn mình hỗ trợ chậm quá, nhiều BV bị á anh.

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.23.0823.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/fd27261f9161607882e4670ac0163081b0bfbc6e)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0823.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/bbaa9421630f15d1ac9d784f11050047d2dcb8aa)
