### ISSUE TITLE
Lỗi - Không gửi tự động XML khi in toa thuốc+mẫu BHYT ở Printer cấu hình số bản in bằng 0

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#113]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/5/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_giarai_guilaixml`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022033447` - _**MaKB**_: `2305000003` - _**MaBA**_: `MaBA` _**NgayKCB**_: `10/5/2023` - _**MaPhong**_: `15` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Services chỉ gửi tự động khi in bảng kê trên module có cấu hình số bản in >0 (in ra giấy mới gửi XML) kể cả in mới hoặc in lại chỉ cần in ra giấy sẽ gửi XML
- Không cấu hình trừ kho trực tiếp nhưng khi in ở Prescription vẫn gửi XML (do BV Giá Rai in bảng kê ở Prescription). 
-> Trường hợp mở khóa chứng từ chỉnh sửa nhưng không in lại trên Prescription chỉ in trên Printer thì phần mềm sẽ không gửi lại XML
hoặc Prescription in bảng kê gửi XML nhưng Printer bấm không lấy thuốc sẽ sinh ra lỗi.

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/034a7a38-3676-4c1b-8ef7-a174dcb033d3)

**Comment by ongtrieuhau** [comment]
Hiện tại đang thiết kế theo hướng nếu in phiếu 01 ra giấy thì mới gửi XML, nên nếu khách hàng sử dụng in phiếu 01 ở Pre thì sau khi chỉnh sửa cũng phải lại đúng chỗ đó để in lại (để ký tên, hoặc hủy phiếu cũ) nên chỗ này services không gửi những hồ sơ này là đúng mục đích thiết kế nhé.
Còn việc phát sinh lỗi khi nhấn không lấy thuốc thì mô tả kỹ thêm trường hợp này nhé.

**Comment by chauthanhtra** [comment]
> Chổ này hiện tại in bảng kê không trừ kho trực tiếp thì Prescription có khóa bệnh đó lại không @chauthanhtra! -> Nếu khóa không cho chỉnh sửa thì gửi xml sẽ đảm bảo không thay đổi dữ liệu! => Trường Prescription không khóa bệnh nhân lại thì có thể chỉnh sửa chẩn đoán hoặc chi phí gây lệch xml gửi tự động và trên phần mềm sau khi chỉnh -> trường hợp này anh @nghivanbi thống nhất lại cách làm hé anh!

- Hiện tại không có khóa nha anh
-

**Comment by chauthanhtra** [comment]
Alo anh @ongtrieuhau 
Trường hợp Prescription in gửi XML rồi Printer bấm không lấy thuốc

Ví dụ: Prescription in bảng kê có thuốc và XML gửi tự động có thuốc thì bảng kê và XML như hình:
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/f8d25d9c-6c64-4022-864c-c59a7cc1f758)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/2cd1e9aa-3a3c-4b6b-9ba6-546ac82e0047)

- Đến khi Printer xác nhận bệnh nhân không lấy thuốc thì XML sẽ thay đổi (xóa phần thuốc) mà không gửi lại XML

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/99c30a2b-533c-4d0c-8994-1d9e7ee9a176)

-> Nếu bệnh nhân không lấy thuốc để gửi lại XML thì phải quay lại Prescription in lại bảng kê 1 lần nữa. Cần có cảnh báo ở Printer hoặc ràng buộc để nhân viên BV biết để in lại trên Prescription

**Comment by ongtrieuhau** [comment]
Ok, **trường hợp Prescription in gửi XML rồi Printer bấm không lấy thuốc**, thì chỗ này Printer sẽ xử lý in ra phiếu 01 luôn nhé (ở trên không nói rõ trường hợp nhấn không lấy thuốc)
