### ISSUE TITLE
Lỗi - Printer không in được bảng kê bệnh nhân BHYT có CLS miễn giảm 100% chi phí

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#115]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/05/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_cairang_bangke_miengiam`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ymV680cDU)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022009184` - _**MaKB**_: `2305008395` - _**MaBA**_: `MaBA` _**NgayKCB**_: `25/5/2023` - _**MaPhong**_: `26` - _**MaDV**_: `01` - _**ThangKT**_: `05` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `CH218` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Printer báo bệnh nhân có chi phí chưa lập phiếu thu đồng chi trả không in được bảng kê (số tiền CLS miễn giảm 100%)
- CLS được miễn giảm 100% chi phí
- Bệnh nhân chưa vượt ngưỡng chi trả của BH

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/cf2e5508-de61-4c3e-940d-83f21c7bb029)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/63f6b30f-7eaf-401b-8e4a-569917492d08)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/f4c35b99-9422-4acd-9f67-8826af316d2e)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0606.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/55c76bac0e49a093c723d3be549faaadbcdd7607)
