### ISSUE TITLE
Lỗi - Bảng kê 6556 của bệnh nhân khám Lao không check loại tuyến KCB của bệnh nhân

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#117]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Ô Môn**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bi_omon_bangke`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/SzlzGDZjz)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023024866` - _**MaKB**_: `2306025468` - _**MaBA**_: `N2023004877` _**NgayKCB**_: `30/6/2023` - _**MaPhong**_: `L01` - _**MaDV**_: `008` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bảng kê 6556 của bệnh nhân khám Lao không check loại tuyến KCB của bệnh nhân (cả ngoại trú và BANT đều bị)

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/0766cb3b-b48b-446b-90cf-8c119fbdfccc)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/afd94773-c722-49fa-a0d3-3c917a459e84)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0630.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/09821b48cffe1517e92a39cc1de395a2d1adf919)

**Comment by nghivanbi** [comment]
Up dll luôn nhé @ongtrieuhau

**Comment by ongtrieuhau** [comment]
Đợi check ok sẽ up dll nhé

**Comment by chauthanhtra** [comment]
ok rồi nha anh @ongtrieuhau 

thêm Prescription luôn nha anh @nghivanbi

**Comment by ongtrieuhau** [comment]
Cập nhật [oLibraries](https://github.com/dh-hos/oLibraries/commit/b919e7c134f86a72519d1cdb90f9c8e76faab88b) nhé @nghivanbi
