### ISSUE TITLE
Lỗi - Không in được phiếu STT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#118]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **03/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023013684` - _**MaKB**_: `2302012465` - _**MaBA**_: `MaBA` _**NgayKCB**_: `03/07/2023` - _**MaPhong**_: `A1.18` - _**MaDV**_: `10` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp trên danh sách có nhiều hơn 1 BN chưa in, thì in ra phiếu STT được bình thường, nếu danh sách chưa in chỉ còn có 1 BN thì không ra phiếu STT được. 
DM máy tính đã có cấu hình máy đó Check in phiếu rồi. 

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/22f398ec-d0dc-4366-9585-3fe203f58e8d)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/fcdc597f-6d9b-42e0-8881-2a4b10c33f49)

**Comment by ongtrieuhau** [comment]
Bệnh nhân nào hông in được cụ thể nhé, chứ test thử thấy in bình thường
[3.pdf](https://github.com/dh-hos/dhg.hospitalprinter/files/11934468/3.pdf)
[4.pdf](https://github.com/dh-hos/dhg.hospitalprinter/files/11934469/4.pdf)

**Comment by ongtrieuhau** [comment]
Có check lại chưa @lqbinh1987 ?

**Comment by lqbinh1987** [comment]
Em đang coi lại anh @ongtrieuhau , tại sáng em về gấp.
Điều kiện là dm máy tính có check In phiếu là đc hả anh? còn điều kiện gì nữa hông anh?

**Comment by ongtrieuhau** [comment]
Uh, và cấu hình trên form option của máy đó nữa

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0704.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/a30dc28492482e00c717400b3598fa1747b4b0b0)
