### ISSUE TITLE
Lỗi - Cảnh báo sai cho đối tượng được Ngân sách hỗ trợ.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#119]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023013692` - _**MaKB**_: `2302012474` - _**MaBA**_: `MaBA` _**NgayKCB**_: `05/07/2023` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `02` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi BN có mã thẻ được hỗ trợ ngân sách từ nhà nước,  ví dụ như Hình1 bệnh nhân có thẻ GD4, mức hưỡng là 20%, nhưng ngân sách hỗ trợ 15% thì còn lại thu của BN chỉ 5%., BN có thuốc và CLS thì Fees đang tính đúng, sẽ tính trên tổng chi phí của BN, không quan tâm đến có thuốc hay không, Printer cũng tính đang trường hợp này.(Hình 2)
Hình 1: 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/b2074aad-9edc-41b1-862b-79f90d17843d)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/cc3a31df-d130-42ea-a99a-449a4c110d68)

Nhưng Printer lại cảnh báo sai, nếu chỉ cls CLS thì Printer vẫn cảnh báo thu 20% và cho phép in lun Hình 3.
Đề nghị bắt lại trường hợp BN chỉ có CLS.
Hình 3:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/f41d4364-a981-4fda-bb41-31f8cf1a53c4)

**Comment by lqbinh1987** [comment]
Nhờ a @ongtrieuhau coi dùm em chổ này, vì hiện tại BV cần cập nhật Printer mới để chặn việc thay đổi số lượng thuốc xuất lớn hơn số lượng của BS ra toa

**Comment by ongtrieuhau** [comment]
Đã chỉnh xong,  @lqbinh1987 trích bệnh nhân này để test lại cho kỹ nhé.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0708.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/03e64b8232aa179386edb7b64b10b1811b3fb10e) (Hiện tại chỉ fix trường hợp thể hiện số tiền bị sai thôi, vì bệnh nhân chỉ có CK+CLS thì không chặn trường hợp này vì trường hợp bệnh nhân bỏ về phải thực hiện in những trường hợp này)
