### ISSUE TITLE
Lỗi - Đối tượng thu phí cho vật tư kèm theo printer nhà thuốc không thấy tên bệnh nhân để phát

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#120]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh Viện Da Liễu Đồng Tháp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieudongthap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023009952` - _**MaKB**_: `2307002656` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/07/2023` - _**MaPhong**_: `06` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `03` - _**MaHH**_: `MaHH` - _**SoHD**_: `K16.00002/07` - _**NgayHD**_: `27/07/2023` - _**ThangKT**_: `07` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `DI48` - _**PhieuYC**_: `PhieuYC`

Bệnh nhân đối thu phí 06 khi Prescription chỉ định cls và check Lấy Vật tư kèm theo, Printer phần IN Phiếu KCB không thấy tên bệnh nhân để phát vật tư (Bệnh viện nhờ kiểm tra lại)

Nhưng khi có cho thêm Toa thuốc thì phần In Phiếu KCB chổ printer mới load lên Toa thuốc và Toa vật tư kèm theo.

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/b12e300c-1252-4ad6-b74c-35469af80518)

```

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/523220f973a4ca1666b22b523f34de8c4ee1d342)
