### ISSUE TITLE
Lỗi - Printer Phục hồi toa in lại giờ lập chứng từ thay đổi 

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprinter#121]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **31/07/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_ungbuou_cdcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/W4WE6LZzO

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023013625` - _**MaKB**_: `2307005287` - _**NgayKCB**_: `31/07/2023` - _**ThangKT**_: `07` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có toa thuốc > In không lấy thuốc > Phục hồi in lại kiểm tra giờ lập chứng từ thay đổi so với lúc In không lấy thuốc

```
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/56a09f5d-8193-4b21-8cb2-6adc20d5d2dc)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/539ec94a-4c4d-4002-9c3c-868b37ae0b27)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/51e6aecd-c405-450e-926f-6e0b5d909f5a)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/0506fc7bc9b9bd5c5fc76f28469a9bdc7e7dca8d)

**Comment by minhduc2it** [comment]
ok
