### ISSUE TITLE
Lỗi - Không ghép được tên bệnh theo công văn 3153/BYT-BH khi khám bệnh nhân Lao

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#124]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/09/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_ghepten`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/t4AhhzIvT)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018007773` - _**MaKB**_: `2309004864` - _**NgayKCB**_: `12/09/2023` - _**MaPhong**_: `57` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân Lao khi khám bệnh cho chẩn đoán Z22.7
khi in bảng kê tại Prescription đã ghép tên bệnh theo mô tả cv 3153/BYT-BH

-> Printer khi in bảng kê set lại tên bệnh không đúng theo mô tả 3153/BYT-BH
```
mô tả 
[Vinh.-.Mo.ta.cap.phat.thuoc.nguoi.benh.Lao.theo.TT36.va.CV3153.-.17-08-2022v2.pdf](https://github.com/dh-hos/dhg.hospitalprinter/files/12583496/Vinh.-.Mo.ta.cap.phat.thuoc.nguoi.benh.Lao.theo.TT36.va.CV3153.-.17-08-2022v2.pdf)

Thông tin bệnh nhân
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/566fa14d-1780-4d5e-9c38-a4b51c39dcda)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/af14020f-e180-447e-9e55-95f6c3ba16f0)

In tại Prescription đã ghép trường psdangky.kqcdoan
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/b49b06eb-67e4-428e-9bb5-4712837c47f9)
khi in ở printer thì set lại trường psdangky.kqcdoan
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/2c31b3ae-cbc5-42c9-b0c3-adf92cdc9851)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0912.6](https://github.com/dh-hos/dhg.hospitalprinter/commit/4a19cd33044395d54ee3830f1b1633a90215e4f0)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Bản này chưa được anh ơi!
trước in
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/9840f48e-b5e5-45e1-92f1-b76d682779f0)
sau in
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/b6f612de-c5b3-4216-a51b-be2bb5cc3b3e)

**Comment by le-an-87** [comment]
Khi bấm in ở printer để xác nhận trừ kho thì phần mềm sẽ set lại chẩn đoán không có ghép tên bệnh theo mô tả anh.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/21a11b23b90f434e37b63e566e5137dbd9878a2b)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
bản mới bấm in bị lỗi anh ơi
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/e466c694-2184-4e74-bb2d-4fd430875358)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/92357c18ab39ae15ce26ba2f8b3eb5d7294fa445)

PS: nhờ @minhduc2it  check giúp bản này còn bị **virus cảnh báo** hông nhé

## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Đã fix!
