### ISSUE TITLE
Lỗi - Không phục hồi được toa nhà thuốc đã bấm Không lấy thuốc của toa nội trú.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#125]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/10/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbnhidong_10_10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023145302` - _**MaKB**_: `2310019842` - _**MaBA**_: `2023029646` _**NgayKCB**_: `13/10/2023` - _**MaPhong**_: ` ` - _**MaDV**_: `02` - _**ThangKT**_: `10` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `Khole` - _**MaHH**_: `MaHH` - _**SoHD**_: `C14.TMN.1013.093525` - _**NgayHD**_: `13/10/2023` - _**ThangKT**_: `10` - _**NamKT**_: `2023`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: ` ` - _**PhieuYC**_: ` `
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Khi đã bấm Không lấy thuốc rồi, bấm Phụ hồi toa lại thì phần mềm lại cảnh báo là **Không đủ tồn kho để phục hồi**

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/3af87b14-d781-4a85-8e98-353701b8fdd3)

**Comment by ongtrieuhau** [comment]
@vuongdh check chỗ này giúp e, vì đang sử dụng dll: **Treat.MR.dll 4.23.330.1**

**Comment by vuongdh** [comment]
[DLL fix lỗi phục hồi toa thuốc nhà thuốc](https://github.com/dh-hos/oLibraries/blob/cb1712485c8e6419a862288ae2bc5d7c021d6972/Treat.MR.dll)

@ongtrieuhau Em cập nhật lại printer dùm anh

**Comment by ongtrieuhau** [comment]
Cập nhật [Printer 3.23.1016.2 ](https://github.com/dh-hos/dhg.hospitalprinter/commit/32c6a558fc86a12f0ed7548d03470ce0709e6e44)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by lqbinh1987** [comment]
Anh @vuongdh , đã bấm **Không lấy thuốc** được, nhưng sau khi bấm xác nhận Không lấy thuốc rồi thì trong tồn kho nó không trừ ra số lượng cột chờ xuất.
Trước khi bấm không lấy thuốc.
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/a38572be-6a74-4ffd-97c4-df21930d4283)

Sau khi bấm Không lấy thuốc, số lượng cột chờ xuất vẫn không trừ, phải làm thao tác **Cập nhật phiếu chưa lĩnh - chưa trả** thì số lượng cột chờ xuất nó mới trừ, trong dữ liệu chỉ cập nhật chungtu.dain=2 và pshdxn.dain=2. Không giống như bấm Không lấy thuốc ở toa ngoại đang làm, là khi bấm Không lấy thuốc sẽ cập nhật chungtu.dain=2, pshdxn.dain=2 và **pshdxn.soluong=0**, trong tồn kho tự trừ vào cột chờ xuất.
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/1b878aa6-df38-4601-a3a5-462073caad1f)

Bấm Không lấy thuốc xong, bấm **Phục hồi** lại cũng không tự động cập nhật lại số lượng cột **Chờ xuất**, phải làm thao tác **Cập nhật phiếu chưa lĩnh - chưa trả** thì mới cập nhật lại số lượng cột Chờ xuất.

**Comment by lqbinh1987** [comment]
Anh @vuongdh  coi chổ này dùm em.

**Comment by vuongdh** [comment]
@lqbinh1987 ok em, em chạy cập nhật nhật xuất xem hết không?

**Comment by lqbinh1987** [comment]
Cập nhật phiếu chưa lãnh chưa trả là nó hết hà anh

Vào Th 4, 25 thg 10, 2023 vào lúc 08:46 Nguyễn Triều Vương <
***@***.***> đã viết:

**Comment by ongtrieuhau** [comment]
Ok

**Comment by lqbinh1987** [comment]
Nhờ anh @ongtrieuhau cập nhật dùm em
