### ISSUE TITLE
Lỗi - khi in phiếu 01KCB 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#133]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_sieuam`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023114771` - _**MaKB**_: `2312006761` - _**MaBA**_: `MaBA` _**NgayKCB**_: `12/12/2023` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Khi bấm vào nút In Toa thuốc + Mẫu BHYT thì lỗi như hình dưới

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/ea95172c-5b9a-488c-9117-ec5ab66b0112)

Chi tiết lỗi 

Error [0]Message: Lỗi code [OTH.Adapter.HosBHXH.AGiamDinh.loadData].

Error [0]HResult: -2146233088
Error [0]Source: OTH.Adapter
Error [0]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV(String pThemoi, EventArgs e, outtv exportTV)
Error [0]TargetSite: Void loadData()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.Couldn't store <System.Byte[]> in oid Column.  Expected type is Int32.
Error [1]HResult: -2147024809
Error [1]Source: OTH
Error [1]StackTrace:    at OTH.ClsPostgres.CmdPgSQL.GetDataTable(String sSQL)
   at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
Error [1]TargetSite: System.Data.DataTable GetDataTable(System.String)

Error [2]=== INNER EXCEPTION ===
Error [2]Message: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.
Error [2]HResult: -2147467262
Error [2]Source: System.Data
Error [2]StackTrace:    at System.Data.Common.Int32Storage.Set(Int32 record, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
Error [2]TargetSite: Void Set(Int32, System.Object)

**Comment by ongtrieuhau** [comment]
Thử dữ liệu khác thử xem

**Comment by hvtuan1987** [comment]
ok anh !

**Comment by hvtuan1987** [comment]
Dữ liệu khác cũng bị luôn á anh Hậu !
Dữ liệu em mới test thêm:  tuan_dbquandanydt_ekip

**Comment by ongtrieuhau** [comment]
Thử server postgres khác xem, thấy dữ liệu này nó hổng tự động được cái oid rồi. 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/58720300/3871d472-e3b3-4ae8-ba35-c3b49ccc899c)

**Comment by hvtuan1987** [comment]
ok anh !
