### ISSUE TITLE
Lỗi - khi in phiếu 01KCB

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#134]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Huyện Thạnh Trị**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbthanhtri_phieu01kcb`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2013025186` - _**MaKB**_: `2312002942` - _**MaBA**_: `MaBA` _**NgayKCB**_: `08/12/2023` - _**MaPhong**_: `28` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Khi vào printer bấm vào nút In Toa thuốc + Mẫu BHYT phát sinh lỗi như hình dưới 
Không in ra được bảng kê nhưng trạng thái đã in và thuốc trừ kho bình thường
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/8d08d09e-c0ae-4afe-be77-78d770a7aa32)

Chi tiết lỗi:

Error [0]Message: Sequence contains no elements
Error [0]HResult: -2146233079
Error [0]Source: System.Core
Error [0]StackTrace:    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OTH.Adapter.HosBHXH.AGiamDinh.CreateBangKeChiPhi()
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.CreateDataSource()
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV_UpdatePSDANGKY_THEN_EXPORT_PRINT6556(ToathuocInfo toathuocInfo)
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV(String pThemoi, EventArgs e, outtv exportTV)
Error [0]TargetSite: TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource])

**Comment by ongtrieuhau** [comment]
Xem [Lỗi](https://github.com/dh-hos/dhg.hospitalprescription/issues/178) nhé 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/58720300/b473fb4d-f405-4589-a041-a3e4134e4705)

**Comment by hvtuan1987** [comment]
@nghivanbi Anh xem lỗi này dùm em á https://github.com/dh-hos/dhg.hospitalprescription/issues/178

**Comment by nghivanbi** [comment]
@ongtrieuhau dll mới bắt cái này hay gì? Các bệnh án ngoại trú khi đăng ký tái khám hiện tại lấy lại chẩn đoán cũ trước đó sẵn.

**Comment by ongtrieuhau** [comment]
Đang lấy thông tin chuẩn đoán theo nhân viên để thể hiện trên phiếu 01. Trường hợp có mã icd thì phải nhân viên chỉ định mã này chứ

**Comment by nghivanbi** [comment]
<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h2>DHG.Hospital Register</h2>
   <h2>v3.23.12.25.1</h2>
  
</div>

## Tập tin cài đặt (Setup Files)

<div align="center">
  
[![Tải về](https://img.shields.io/badge/Tải%20file%20cài%20đặt-Google-blue?logo=googledrive)](https://drive.google.com/drive/folders/15qNx6iZavpvO9PHl--bCKCwfUNAR0v6y) 
  
</div>

## Nội dung cập nhật

<div align="center">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalregister/blob/main/Deploy_Tools/CHANGELOG.md)

</div>
