### ISSUE TITLE
Lỗi - Printer BHYT in toa Nghiện - Hướng thần

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprinter#135]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan_toaht`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/sBeWcWrCa

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020006338` - _**MaKB**_: `2312003195` - _**MaBA**_: `N2023000146` _**NgayKCB**_: `21/12/2023` - _**MaPhong**_: `08` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```

```
Printer tham số kd.toathuoc = 0: Khi bấm nút In toa thuốc + Mẫu BHYT  thì chỉ in Phiếu 01 thôi. **Không cần in ra toa** (thuốc BHYT thường và **thuốc Nghiện-Hướng thần**)
Hiện tại BN Có toa thuốc BHYT thường và thuốc Hướng thần thì Printer không in toa thuốc BHYT thường, **mà in ra 3 toa thuốc Hướng thần**

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/16a30de9-42d8-4aa0-a6c7-45670ce15414)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/672d7a39-8085-4f24-abe6-f26fdc4a2a6e)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0518.4 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405184-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405184-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405184-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Thêm chức năng cho phép cấu hình in toa nghiện, hướng thần khi tham số kd.khoaduoc=0

![](https://i.imgur.com/i2ydDCH.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/135

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
tham số kd.khoaduoc không có

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/f66dddfe-4c08-41f6-8acc-212bf3b594b8)

**Trên Pm hiện tại chỉ có tham số kd.toathuoc**
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/98a36cd2-858c-492e-8f4d-d52ce8526206)

**Comment by ongtrieuhau-dh** [comment]
Cái này sai tên tham số khi gõ thôi, nhưng chức năng vẫn có, giao diện sẽ chỉnh lại trong bản tiếp

**Comment by minhduc2it** [comment]
Chức năng đã test ok
Kiểm tra bệnh nhân mới chưa phát hiện lỗi. Các chức năng Thu phí, bảng kê 6556, XML xuất bình thường
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/b80b7321-cc83-4541-941b-1108a67ca581)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/07743807-760b-49bd-b7ef-0016648618b8)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/7502e6d6-e57a-4e21-932b-be014e76899f)
