### ISSUE TITLE
Lỗi - Lệch số lượng xuất khi đối chiếu Bảng kê-> Tổng hợp theo sản phẩm và Bảng kê -> Hóa đơn nhà thuốc

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#138]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **24/01/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_q12_20240118_085327`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `AU23` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`
**Mã hàng AU23 Tổng xuất trong tháng là 718 nhưng vào Printer. Bảng kê -> Hóa đơn nhà thuốc (Theo sản phẩm lại ra 808 )**
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/b2cdb6c6-549c-4eac-ab07-13802a2232ac)

Báo cáo tháng-> Tồn kho chẵn
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/8159ad87-c286-4f55-b950-f3c04dacf306)

Bảng kê-> Hóa đơn nhà thuốc tại Printer
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/c80dfbef-e58e-495f-afe3-5d6f12d0e9c7)

**Comment by ongtrieuhau-dh** [comment]
Kiểm tra lại xem có thuốc nào có xuất là chưa xuất hóa đơn hông?

**Comment by hvtuan1987** [comment]
Này số lượng trong Hóa đơn nhà thuốc lớn hơn số lượng Tổng xuất của thuốc đó trong tháng luôn áh !

**Comment by hvtuan1987** [comment]
Dạ để em coi á !

**Comment by hvtuan1987** [comment]
Hiện tại em kiểm trong bảng pshdxn cùng mã khách hàng không thấy có phát sinh khác số hóa đơn á !
Em kiểm thử ngày 07/01/2024  là đã thấy lệch. Xuất trong ngày 24 mà tróng Hóa đơn nhà thuốc ra 52 !
