### ISSUE TITLE
Lỗi - In Toa thuốc và Vật tư y tế tại Printer lấy sai tiêu đề

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#139]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92017`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Da Liễu thành phố Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbdalieu_toathuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024020736` - _**MaKB**_: `2404007970` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/04/2024` - _**MaPhong**_: `5` - _**MaDV**_: `10` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `02` - _**MaHH**_: `GAC22` ,'GON02'- _**SoHD**_: `AB5.00859/202404` - _**NgayHD**_: `19/04/2024` - _**ThangKT**_: `04` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)

[-] Printer Kho lẻ nhà thuốc
Bệnh viện đang in Toa thuốc + Phiếu thu tại printer 
Trường hợp bệnh nhân có 2 Toa, Một toa là Vật tư và Một  Toa là thuốc thì Toa có Vật tư y tế hiển thị sai như hình dưới
(Tiêu đề phải là đơn thuốc nhưng lại hiển thị là PHIẾU THU)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/0091fca9-d41f-4509-b964-7222721fd1a9)
Bệnh viện nhờ chỉnh lại nếu là vật tư thì Để Tiêu đề là TOA VẬT TƯ
Tất cả đối tượng và BHYT và THU PHÍ Nếu có 2 toa trong trường hợp trên đều in ra sai tiêu đề

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprinter/139)
<details> <summary>   ℹ️<code>2024-19-04 13:19:41</code> <code>@hvtuan1987</code><code>projects_v2_item.created</code>   <code><code>[<a href='https://o-dh-003-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/-Nvp-gERgyxNBcTMon4n'>-Nvp-gERgyxNBcTMon4n</a>]</code></code><code>GH</code> </summary> <code>[bot]</code><code>1.24.0321.1600@gh-dh-hos-more-alien-weekly-ubuntu-latest-gh-svr-listen-yml-1713506994476</code><code>[<a href='https://github.com/dh-hos/more-alien-weekly-ubuntu-latest/actions/runs/8749191964'>webhook-logs</a>]</code></details>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0601.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406010-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406010-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406010-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - In Toa thuốc và Vật tư y tế tại Printer lấy sai tiêu đề

![](https://i.imgur.com/9obPAFx.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/139

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã ok rồi á !
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/5e648d10-2de9-4d6f-828f-42fbbc0b2cd5)
