### ISSUE TITLE
Lỗi - Không phục hồi được toa mua ngoài không lấy thuốc và không in bảng kê

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#141]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51219`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PKĐK Minh Quang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_timmach_ct_lechtien_02022024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/FRAMK0Aql)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `24000007` - _**MaKB**_: `2402001560` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/2/2024` - _**MaPhong**_: `21` - _**MaDV**_: `01` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

(Đổi data do lỗi máy chủ mất data PK)

Bệnh nhân BHYT có toa mua ngoài -> vào Printer nhà thuốc -> không lấy thuốc -> chọn không in bảng kê -> không phục hồi được toa do không tìm thấy tên bệnh nhân để mở khóa và danh sách bệnh nhân không lấy thuốc cũng không có bệnh nhân , phải vào tất cả toa mới có thông tin nhưng không phục hồi được do không mở khóa được

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/5d3fdd50-00da-4264-9869-a686775414f6)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/97de3c40-e21d-4ba0-9ae1-ed612c30dbee)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/a622c83b-5e3e-47cc-a4f2-347b72bbb153)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/229b10e4-aca7-4112-aa35-f131b6351c4d)

**Comment by ongtrieuhau-dh** [comment]
Cái này tạm thời hướng dẫn ra toa thêm đi, vì vướng cùng chung trạng thái với BHYT nên khó xử lý, đợi cải tiến chỗ này thêm tách riêng trạng thái theo toa mới được.

**Comment by chauthanhtra** [comment]
ok anh
