### ISSUE TITLE
Lỗi - Printer Bệnh nhân có phát sinh % cùng chi trả có bật tham số chặn không cho in phiếu 01KCB nhưng vẫn in được

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#145]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận 12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbquan12_01kcb`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024002083` - _**MaKB**_: `2401014160` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/01/2024` - _**MaPhong**_: `A1.14` - _**MaDV**_: `10` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `DA231` - _**SoHD**_: `B24.00161/202401` - _**NgayHD**_: `11/01/2024` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân có phát sinh % cùng chi trả có bật tham số chặn không cho in phiếu 01KCB nhưng Printer vẫn cho in
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/85f10f38-4aff-4d77-bced-8b6fdd6fe7d0)

Phiên bản Printer 3.24.0203.1
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/e6cddde8-78ba-4935-84da-388254c9e181)
Hiện tại em đã mở khóa bệnh nhân đó ra rồi á. Khi nào kiểm anh bấm in lại thử áh !

```

**Comment by ongtrieuhau-dh** [comment]
Ok, để kiểm tra lại

**Comment by ongtrieuhau-dh** [comment]
Nghiệp vụ liên quan tới kho thuốc, mà chưa thấy thông tin của
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/7f9b7419-020a-491b-9db7-6b7745712814)

**Comment by hvtuan1987** [comment]
Em có bổ sung thêm rồi áh !

**Comment by ongtrieuhau-dh** [comment]
Fix lỗi tại [SetupHospitalPrinter.v3.24.0305.1.msi](https://gofile.me/78TQg/YKs2j65E7)

**Comment by hvtuan1987** [comment]
ok anh !

**Comment by hvtuan1987** [comment]
Đã ok !
