### ISSUE TITLE
Lỗi - Chưa đến ngưỡng thu vẫn không in được phiếu 6556.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#146]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/03/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `bvq122023041412_2403008438_`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022113387` - _**MaKB**_: `2403008516` - _**MaBA**_: `MaBA` _**NgayKCB**_: `07/03/2023` - _**MaPhong**_: `A1.04` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tông chi phí của BN chưa vượt ngưỡng thu(270,000), nhưng Printer vẫn cảnh báo chưa thu tiền như hình dưới.
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/4a679868-1dfc-4def-adb8-e4f1b7197e4d)

Nhưng cũng BN khác, cũng chưa vượt ngưỡng thì lại in được như BN này:
  > _**MaBN**_: `2023012887` - _**MaKB**_: `2403008500` - _**MaBA**_: `MaBA` _**NgayKCB**_: `07/03/2023` - _**MaPhong**_: `A1.04` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/5d7ec306-5dd4-4648-a1ab-e08c6512e695)

**Comment by ongtrieuhau-dh** [comment]
Đã tiếp nhận

**Comment by ongtrieuhau-dh** [comment]
Fix lỗi tại [SetupHospitalPrinter.v3.24.0308.1.msi](https://gofile.me/78TQg/V96ATAEsL)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau , Lỗi trên đã fix đc đối với BN khám bệnh mà không có chi phí ngoài BHYT.
Những vẫn còn đang lỗi trường hợp BN Khám bệnh có chỉ định CLS không thanh, đã thu CLS không thanh, còn lại phần tổng tiền BHYT chưa vượt ngưỡng, nhưng printer vẫn không cho in, báo lỗi như hình.
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/13183708-b380-489a-85bc-1a961480e2ad)
Thông tin BN: 
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024016956` - _**MaKB**_: `2403008595` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/03/2024` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

**Comment by ongtrieuhau-dh** [comment]
Đã tiếp nhận

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupHospitalPrinter.v3.24.0311.2.msi](https://gofile.me/78TQg/ft41H7yZZ)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau .
Vẫn còn lỗi đối với trường hợp BN có phần trăm ngân sách hỗ trợ, có chi phí ngoài BHYT, đồng thời chi phí trong BHYT cũng vượt ngưỡng thu, Fees đang tính đúng: Tổng chi phí là 314,345, trừ chi phí ngoài BHYT **21,800**, còn lại 292,545, BN có mức hưởng là 80%, cộng thêm ngân sách hỗ trợ 15%, BN đóng 5% của 292,545 là **14,627**
=> % cùng chi trả 14,627 + chi phí ngoài BHYT 21,800 = **36,427**
Mà printer lại báo số tiền khác là 33,157
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/9d580220-3e39-43d5-8ddc-9b13200ef616)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/6af7dd2b-6b44-4e7d-b0f3-f000a871a453)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/b4cb388f-7484-4b3e-9167-fa7b3ba00d21)

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau ơi tranh thủ dùm em cái này, bản mới bị vướng nên trả về bản cũ, mà bản cũ thì lỗi vượt ngưỡng chưa thu mà vẫn cho in, gây thất thoát cho BV

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [SetupHospitalPrinter.v3.24.0315.1.msi](https://gofile.me/78TQg/NIhiiZ6ku)

**Comment by lqbinh1987** [comment]
Đã ok.
