### ISSUE TITLE
Lỗi - BN ngoại trú khám YHCT cột psdangky.kqcdoan ghi nhận double chẩn đoán

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprinter#147]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) **74206**
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Medic Miền Đông**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_medicmd_cdoan`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/K6xzjDtO7

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022076123 ` - _**MaKB**_: `2403000271 ` - _**MaBA**_: `MaBA` _**NgayKCB**_: `01/03/2024` - _**MaPhong**_: `11` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```

```
Printer in Phiếu 01 chẩn đoán chính và Chẩn đoán phụ hiển thị nội dung: 
    + Chẩn đoán chính: Nhục tý [Đau cơ]
    + Chẩn đoán phụ: Dãn tĩnh mạch chi dưới
Bảng psdangky.kqcdoan ghi nhận= Nhục tý [**Đau cơ**];Dãn tĩnh mạch chi dưới;**Đau cơ**
**Bị double: Đau cơ**

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/3ee5476e-9eaa-49bb-a584-e875e2ea1774)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/6f5f9fd9-a824-4056-ac4a-2f10e35c9986)

**Ps: Khách hàng yêu cầu hỗ trợ sớm, Thứ 2 tuần sau BHYT Giám định**

**Comment by ongtrieuhau-dh** [comment]
Hiện  tại bệnh viện yêu cầu hỗ trợ thế nào?

**Comment by minhduc2it** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/05853000-1552-4004-83c9-2c5890c69188)

**Comment by ongtrieuhau-dh** [comment]
> Ps: Khách hàng yêu cầu hỗ trợ sớm, Thứ 2 tuần sau BHYT Giám định

Chỉ đối với bệnh nhân này hay sao?

**Comment by minhduc2it** [comment]
Hiện tại  chỉ BN ngoại trú khám YHCT bị.
dữ liệu bị từ tháng 2 đến hiện tại

**Comment by ongtrieuhau-dh** [comment]
Xin dữ liệu đầy đủ và nhờ @nghivanbi hỗ trợ xử lý nhé, vì cái này làm làm theo mô tả khi xử lý ghép chẩn đoán, có theo tham **số xml4210.yhct**

**Comment by ongtrieuhau-dh** [comment]
Phần module mới, bản cập nhật tới sẽ hỗ trợ thêm kiểm tra trường hợp này nữa để tránh bị trùng khi có nối chuỗi có kèm bệnh YHCT

**Comment by minhduc2it** [comment]
Bản cập nhật fix lỗi

Kiểm tra bệnh nhân mới chưa phát hiện lỗi. Các chức năng Thu phí, bảng kê 6556, XML xuất bình thường
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/3b028845-9dad-4c04-825e-2ec96832d21a)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/8a44ff24-a6c3-4b48-8673-b3f0a04fa011)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/74914306-ab5f-4fc4-9580-ed53a40c80de)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/dc4721e4-579d-4019-9685-e92776663663)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/98437757/3d233841-0a3d-4d94-898d-10c2a689eab0)
