### ISSUE TITLE
Lỗi - Cảnh báo sai số tiền chưa thu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#148]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12_printer_koindc_bn2toa`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://dhsolutions.synology.me:5001/d/s/xhXg1ce4XQdpkoNxYELqOkI13WOMtCRM/DuwBVoh5To6O1QW5xGIFqU699ckB4tWb-zLmgY71dOAs)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023025590` - _**MaKB**_: `2403019400` - _**MaBA**_: `MaBA` _**Ngày KCB**_: `18/03/2024` - _**MaPhong**_: `A1.14` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN này có 2 toa, có vượt ngưỡng thu %CCT, nhưng printer lại cảnh báo sai số tiền mà BN CCT so với Fees
Không phải BN nào trường hợp này cũng bị, trường hợp này em có tạo thêm 1 BN, cũng chỉ định 2 toa và chỉ chỉ định cls giống vậy luôn mà không bị
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/bef13d4b-7439-41bf-bf9f-cecdea893896)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/39814dcf-36bb-4700-9d03-ffcdcab23e88)

_**Không phải BN nào trường hợp này cũng bị, trường hợp này em có tạo thêm 1 BN, cũng chỉ định 2 toa và chỉ chỉ định cls giống vậy luôn mà không bị**_
**Thông tin BN giống vậy mà không bị:**
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2403019401` - _**MaBA**_: `MaBA` _**Ngày KCB**_: `19/03/2024` - _**MaPhong**_: `09` - _**MaDV**_: `10` - _**ThangKT**_: `03` - _**NamKT**_: `2024`
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/540585e2-396a-4928-915b-e08cf4902e30)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại📣

**Comment by ongtrieuhau-dh** [comment]
Tiếp nhận

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0517.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405171-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405171-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405171-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi cảnh báo sai số tiền trên form ![image](https://i.imgur.com/JCGGlH0.png)

Nguyên nhân do module ghi nhận phiếu phẫu thuật bị double row. Cái này phải ghi nhận lại để module Prescription kiểm tra lại. ![image](https://i.imgur.com/7ccdrBw.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/148

<div align="right">

[![View](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![View](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh)
</div>

**Comment by lqbinh1987** [comment]
OK, printer đã fix, để em kiểm bên Pre.
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/c3b7ac10-8bd2-4919-b021-33b305bb4e6f)
