### ISSUE TITLE
Lỗi -  Chức năng Mở khóa và xóa giờ kết thúc khám ở kho nhà thuốc xóa ICD, chẩn đoán, ngày in phiếu BHYT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#149]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/03/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_so10_02_032024_ngayylenhsauketthuc_19032024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/GqVtVeZcM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024007208` - _**MaKB**_: `2402010022` - _**MaBA**_: `MaBA` _**NgayKCB**_: `19/02/2024` - _**MaPhong**_: `19` - _**MaDV**_: `10` - _**ThangKT**_: `02` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lỗi chức năng Mở khóa và xóa giờ kết thúc khám ở kho nhà thuốc

Trường hợp bệnh nhân BHYT có toa mua ngoài đã in bảng kê BHYT kết thúc khám ở kho BHYT và kho nhà thuốc, nếu chọn mở khóa và xóa giờ kết thúc khám ở Printer nhà thuốc thì phần mềm xóa ICD, chần đoán và ngày giờ in phiếu BHYT (bảng psdangky)
-> Fix lỗi chức năng Mở khóa và xóa giừo kết thúc khám ở kho nhà thuốc

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/95bf3f4f-19bf-42e3-b468-cbe5f1e0f0ba)

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprinter/149)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0601.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Ẩn chức năng Mở khóa và xóa giờ kết thúc khám đối với nhà thuốc

- 🐛: Lỗi - Chức năng Mở khóa và xóa giờ kết thúc khám ở kho nhà thuốc xóa ICD, chẩn đoán, ngày in phiếu BHYT

![](https://i.imgur.com/cZ0pQ9R.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/149

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
> ### 📣📣📣 HospitalPrinter.exe v.3.24.0601.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32406011-NasDHSolutions.json)
> ## Nội dung thay đổi
> 
>     * ✨: Ẩn chức năng Mở khóa và xóa giờ kết thúc khám đối với nhà thuốc
> 
>     * 🐛: Lỗi - Chức năng Mở khóa và xóa giờ kết thúc khám ở kho nhà thuốc xóa ICD, chẩn đoán, ngày in phiếu BHYT
> 
> 
> ![](https://camo.githubusercontent.com/6420eee8fc2b75fc81fa0fee4f8607d4f273febd019db41472b5e33f86c349c1/68747470733a2f2f692e696d6775722e636f6d2f635a30705139522e706e67)
> 
>     * ☑: [Lỗi -  Chức năng Mở khóa và xóa giờ kết thúc khám ở kho nhà thuốc xóa ICD, chẩn đoán, ngày in phiếu BHYT #149](https://github.com/dh-hos/dhg.hospitalprinter/issues/149)
> 
> 
> [![](https://camo.githubusercontent.com/d35801e5d044884ef8d71e71ab0e09423cebd7d135c21558eb1a56e17946868d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d54682545312542422542316325323068692545312542422538376e25323062254531254242253946692533412532302534306f6e6774726965756861752d2d64682d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/ongtrieuhau-dh) [![](https://camo.githubusercontent.com/8375d1042897ab92159f8fc4de5d61a4a3b7586baa3d15442c948f68a357f76c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d58656d2532306c2545312542422538426368253230732545312542422541442532307068692543332541416e253230622545312542412541336e2d696e666f726d6174696f6e616c3f6c6f676f3d676974687562)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://camo.githubusercontent.com/d21df0e2392d69e70bbbda45fa7304196e57abd1cfa17878b66b0b728a485153/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4e682545312542412541446e25323074682543332542346e67253230622543332541316f25323074722543332541416e25323054656c656772616d2d3243413545303f7374796c653d666c61742d73717565617265266c6f676f3d74656c656772616d266c6f676f436f6c6f723d7768697465)](https://t.me/dhhoscodemsifiles)

- Phần mềm Printer đã ẫn chức năng Mở khóa và xóa giờ kết thúc khám trên Printer nhà thuốc

 ![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/0bfc7a08-8878-491d-8bfc-41f16b1ee305)

- Test bệnh nhân mới chưa phát hiện lỗi mới in bảng kê, xuất XML bình thường ,  ẫn chức năng Mở khóa và xóa giờ kết thúc khám trên Printer nhà thuốc

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/e894daaa-9c1b-405a-8f32-a323ec1abf3a)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/bf36791b-58b6-49fc-bba8-32041e3e98e4)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/84fe7c26-1a36-475c-8431-a40aeb23e365)
