### ISSUE TITLE
Lỗi - Bệnh nhân nội trú không in được phiếu thu từ kho nhà thuốc

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#150]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **16/04/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện đa khoa Thành phố Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbtpct_chungnhanmien`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023079967` - _**MaKB**_: `2312020054` - _**MaBA**_: `039462` _**NgayKCB**_: `16/04/2024` - _**MaPhong**_: `202` - _**MaDV**_: `03` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `AG52` - _**SoHD**_: `Z70.R24.0416.164746` - _**NgayHD**_: `16/04/2024` - _**ThangKT**_: `01` - _**NamKT**_: `2024`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân nội trú Xuất viện lập toa Ngoại trú lấy từ nhà thuốc như hình dưới
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/9269ca47-bf5c-4843-a043-a11880b42d9d)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/6c040f56-a55d-4340-ba60-f93ad9453705)

 - Printer : Bấm vào nút In toa thuốc + Phiếu thu chỉ in ra được Toa thuốc mà không in ra được phiếu thu.
 Bệnh viện nhờ Fix in ra được Toa thuốc và phiếu thu giống bệnh nhân ngoại trú

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/3670f636-0bc6-4535-961e-05b6c2c98046)

Trong ngày 16/04/2024 Em có nhập bệnh nhân ngoại trú  tên  THU 2  in Toa thuốc và phiếu thu anh có thể xem thử phiếu thu)

```

**Comment by gh-dh-bot-00** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprinter/150)

**Comment by chauthanhtra** [comment]
Có phần mềm fix nhắn em nha anh @hvtuan1987 
BV Số 10 cũng báo lỗi này. Printer mới không in được phiếu thu toa xuất viện nhà thuốc

**Comment by ongtrieuhau-dh** [comment]
Cập nhật [Setup-HospitalPrinter.exe.v3.24.0510.0.msi](https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBbjd3eUx2VWlHdnNnUWNJQkxNLUdhQUdyQ0dH/root/content).
Yêu cầu test kỹ các khâu từ cài đặt, phiên bản đè, cập nhật tự động do mới áp dụng build tự động

**Comment by hvtuan1987** [comment]
@ongtrieuhau Đã test và chưa in được phiếu thu đối với bệnh nhân nội trú á !

**Comment by ongtrieuhau-dh** [comment]
Cập nhật bản mới nhất [tại đây](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) thử nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0518.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405183-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405183-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405183-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Bệnh nhân nội trú không in được phiếu thu từ kho nhà thuốc

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/150

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Vẫn chưa in được phiếu thu á anh @ongtrieuhau 
Em đã cài lại bản mới 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/6822a0b9-0805-4750-86a0-1ff9c471dbaf)

**Comment by ongtrieuhau-dh** [comment]
Nhờ @hvtuan1987 cập nhật link dữ liệu để thử ngoài công ty nhé

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0522.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405220-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405220-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405220-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không in được phiếu thu đối với Nhà thuốc

![](https://i.imgur.com/l7Cmjgf.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/150

- 📕: Fix code kiểm tra tham số `DongvaTayDuoc` bị sai

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by hvtuan1987** [comment]
Đã in được rồi á !
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/482e1e4b-3efc-40a0-b3de-add755beb021)
