### ISSUE TITLE
Lỗi - Bệnh nhân có nhập giấy Chứng nhận miễn nhưng bảng kê 6556 vẫn có tiền phát sinh cùng chi trả (BV Ung Bướu)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#152]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **17/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_ungbuou_cnmien_17052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`an_ungbuou_cnmien_17052024`](https://gofile.me/78TQg/mh5ybflNi)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000002` - _**MaKB**_: `2405005461` - _**NgayKCB**_: `17/05/2024` - _**MaPhong**_: `11` - _**MaDV**_: `16` - _**ThangKT**_: `05` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân có nhập giấy chứng nhận miễn
-> Bảng kê 6556 vẫn phát sinh tiền cùng chi trả.

=> Module printer và Prescription đều có phát sinh cùng chi trả.

```
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/31241329-dd25-4c49-a091-53cfb9923115)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/c6a34d00-77a4-4c73-b6fd-d6181fab4c6d)
Bảng kê in tại Printer
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/4e60d0fc-66fc-441a-807f-89e57efd674d)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprinter/152)

**Comment by ongtrieuhau-dh** [comment]
Hai cái hình đâu có cái nào có cùng chi trả đâu @le-an-87

**Comment by le-an-87** [comment]
Lỗi em kiểm tra không kỹ nên ghi nhận sai.
