### ISSUE TITLE
Lỗi - Load sai toa thuốc khi in toa

### ISSUE THREAD

**Issue by lequocthong29** [dh-hos/dhg.hospitalprinter#153]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lê Quốc Thống**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `93102`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Đa Khoa số 10**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `thong_dbso10_kyso`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1_6KmRr4BVFv2jsqk_mQ9XyAu6JYfAk25/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)
- Khi in toa thuốc không có madonthuoc ([hình 1](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/b3cb6631-3c6b-4260-9a54-c36bffded387)), file toa thuốc đã ký được lưu lại trong thư mục cài đặt với tên như ([hình 2](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/e6848f0d-5525-4a99-bf93-fb208d1a78b1)). Khi in một toa khác bất kỳ củng không có matoathuoc thì file toa thuốc đã ký không được lưu lại, thay vào đó phần mềm load lại file đã lưu trước đó ở ([hình 2](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/e6848f0d-5525-4a99-bf93-fb208d1a78b1)) để in ra, dẫn đến in sai toa thuốc.

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/b3cb6631-3c6b-4260-9a54-c36bffded387)
Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/e6848f0d-5525-4a99-bf93-fb208d1a78b1)

**Comment by ongtrieuhau-dh** [comment]
Thử bản mới nhất xem còn bị hông nhé @lequocthong29  [Chi tiết cập nhật](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme)

**Comment by ongtrieuhau-dh** [comment]
Nếu vẫn còn bị, thì vào code HospitalToaThuoc này để xem lỗi thế nào nhé, vì chỗ này sếp @nghivanbi đang chỉnh á

**Comment by lequocthong29** [comment]
> Thử xem bản mới nhất còn thiết bị hông nhé@lequocthong29 [Cập nhật chi tiết](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme)

bản này hiển thị đang nạp dữ liệu không tắt a 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/e7e689e9-a137-4f28-9bfc-24f181e65cf2)
- khi ấn in toa thì hiện thông báo như hình, ấn đồng ý xong bấm in lại vẫn bị 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/110148171/8cff4469-cd67-43cd-b56d-ab954b57314f)

**Comment by ongtrieuhau-dh** [comment]
Cập nhật link dữ liệu để anh thử ở ngoài công ty nhé @lequocthong29

**Comment by lequocthong29** [comment]
> Cập nhật link dữ liệu để anh thử ở ngoài công ty nhé @lequocthong29

E cập nhật rồi nha a!!! 
* [database](https://drive.google.com/file/d/1_6KmRr4BVFv2jsqk_mQ9XyAu6JYfAk25/view?usp=sharing)

**Comment by ongtrieuhau-dh** [comment]
Ok, đã nhận

**Comment by ongtrieuhau-dh** [comment]
2 lỗi trên thì check lại trường oid trong bảng chidinhcls và pshdxn nhé. ![](https://i.imgur.com/PWZghye.png). 
Còn lỗi thông tin bệnh nhân chưa đúng thì hông có xảy ra khi bỏ cái tham số `cks.url`, nên anh đoán là do lỗi chỗ này mới gây ra chỗ đó. Em check lại nhé @lequocthong29 , hoặc hướng dẫn để có cái chữ ký số này để test full luồng mới được.
![](https://photos.app.goo.gl/rMgXuCCcReuASrQ9A)

**Comment by lequocthong29** [comment]
- lỗi thông tin bệnh nhân chưa đúng e test thử chạy từ file DebugPrinter (phiên bản hiển thị là 1.24.0517.0) thì không báo lỗi  còn khi cài đặt file setup (phiên bản hiển thị là 3.24.0517.0) xong chạy thì báo lỗi á a. Trường hợp có và không có cks.url đều báo lỗi như nhau.
* cks.url = http://api.dh-his.com:3002/kyso/softdream (a muốn test trường hợp có cks.url thì add link này nha)
// chữ ký được map với manv, do đang chỉ có 1 chữ ký demo map mã 00 nên a set current.chungtu.manv = 00 để ký hợp lệ nhé !

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0518.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405180-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không build được dll mới trên hệ thống build tự động

![](https://i.imgur.com/EcJSMmr.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/153#issuecomment-2118137206

- 📕: Build lại và kiểm tra build tự động không lấy được phiên bản mới

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0518.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405181-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405181-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32405181-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix lỗi không build được dll mới trên hệ thống build tự động

![](https://i.imgur.com/EcJSMmr.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/153#issuecomment-2118137206

- 📕: Build lại và kiểm tra build tự động không lấy được phiên bản mới

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
