### ISSUE TITLE
Lỗi - Chưa thông báo được trạng thái đã thanh toán khi đã thanh toán QR thành công.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#154]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_ttntqn_trangthaitt`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://dhsolutions.synology.me:5001/d/s/ydRENeOoqiUtTXioZX1Gvhn7DhlQvD6D/wWte3FWZm-6Pp-SBMoVxf1We6FZ_9IHq-mb8AeQxMZAs)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023000569` - _**MaKB**_: `2405005861` - _**MaBA**_: `MaBA` _**NgayKCB**_: `27/05/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiển tại printer gen QR, đã quét thanh toán, tiền đã chạy vào tk  của BV, rên merchant trạng thái đã success(Hình1) nhưng khi check trạng thái thanh toán thì phần mềm báo là **Chưa thanh toán**(Hình 2), trong fie log tại BV(....\winston-logs) có ghi lại thông tin như sau:
```[2024-05-27 08:51:23.108 AM] info: 	eventQueue.processStack.started [0]:::-Nyrjg3BsAji9Z3UoZ94:::{"amount":"310200","bankTransactionId":"1YFFQ-7rUmQEvt8","merchantId":"4300278035","merchantName":"BV NOITIET","orderId":"XPPNYVPVGPXI","productId":"","requestId":"584757662","signature":"fvN/j/OalXa4mbxj94gyfNuOH7tN4Pw1asMQATDKDHiiCpsvXEpfEO81o3Sswal3iE7E123HXAgdbHbsxOSB/zzc8wjGBu6qSWae0VO/c9TSyMT1fxlW+k6m+8l7rS8P3njmp7j9xYcG6bqYhle4XcCC8mf/h2yYEomdoQHQ68+YJJ5hIk7Y5zv66YKuaE7hWrURlWtVGFBNYQxlDlMBlL+c2s3oljbNBeCedGgNX6mnqmN9w1AMNFbOtO+81sffeJJ1k3Je6lsaVXltSFXT3CwRLvc9yffrIDEAFY9iFuNAjvHGzoozDLVTw+KglH0NC4bhR9iQ8eZ7+yTkvpMIgQ==","statusCode":"00","statusMessage":"Tru tien thanh cong, so trace 584757662,TTQR-XPPNYVPVGPXI-584757662-0000000000-VIETCOMBANK-******0000","terminalId":"QUAYTHUOC","transactionDate":"20240527085121"}
[2024-05-27 08:51:23.476 AM] info: 	executeSQL.input
                                     [ "\n          UPDATE current.thuchi SET pay_type = 'QRCODE', thucthu_pay=310200, pay_payid = 'XPPNYVPVGPXI' WHERE pay_qrid='XPPNYVPVGPXI' RETURNING *;\n          ", undefined ]
[2024-05-27 08:51:23.477 AM] info: 	executeSQL.result
                                     []
[2024-05-27 08:51:23.479 AM] info: 	await pgSQL.executeSQLToHIS(qrid='XPPNYVPVGPXI', thucthu_pay='310200');
[2024-05-27 08:51:23.479 AM] info: 	eventQueue.processStack.finished [0]:::-Nyrjg3BsAji9Z3UoZ94:::{"amount":"310200","bankTransactionId":"1YFFQ-7rUmQEvt8","merchantId":"4300278035","merchantName":"BV NOITIET","orderId":"XPPNYVPVGPXI","productId":"","requestId":"584757662","signature":"fvN/j/OalXa4mbxj94gyfNuOH7tN4Pw1asMQATDKDHiiCpsvXEpfEO81o3Sswal3iE7E123HXAgdbHbsxOSB/zzc8wjGBu6qSWae0VO/c9TSyMT1fxlW+k6m+8l7rS8P3njmp7j9xYcG6bqYhle4XcCC8mf/h2yYEomdoQHQ68+YJJ5hIk7Y5zv66YKuaE7hWrURlWtVGFBNYQxlDlMBlL+c2s3oljbNBeCedGgNX6mnqmN9w1AMNFbOtO+81sffeJJ1k3Je6lsaVXltSFXT3CwRLvc9yffrIDEAFY9iFuNAjvHGzoozDLVTw+KglH0NC4bhR9iQ8eZ7+yTkvpMIgQ==","statusCode":"00","statusMessage":"Tru tien thanh cong, so trace 584757662,TTQR-XPPNYVPVGPXI-584757662-0000000000-VIETCOMBANK-******0000","terminalId":"QUAYTHUOC","transactionDate":"20240527085121"}
```
Trong pay.exchange hổng thấy dl củ giao dịch này luôn.

Hình 1:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/8f6b9d05-11f0-4731-b498-cfef26acb1b7)

Hình 2:
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/4635fe76-2788-4a56-b49d-1835bbe6dbdc)

**Comment by ongtrieuhau-dh** [comment]
Cái này chạy cái workflow lại, cho nó lấy cái mới rồi thử lại nhé,

**Comment by lqbinh1987** [comment]
OK anh để e thử

**Comment by lqbinh1987** [comment]
Đã chỵ workflow lại, vẫn không đc nhe anh @ongtrieuhau, trong fie log ...\dh-hos\51214-qrcode-vietin\winston-logs có ghi lại thông tin như phí trên đầu git em có nhắn.
Trong pay.exchange hổng thấy dl của giao dịch đó lun.

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/6582da78-8e43-425b-a474-be20ba99c200)

**Comment by ongtrieuhau-dh** [comment]
lấy mấy file log về xem nhé
có chữ log

**Comment by lqbinh1987** [comment]
[main.js-2024-05-27.info.log.txt](https://github.com/dh-hos/dhg.hospitalprinter/files/15481388/main.js-2024-05-27.info.log.txt)
File ngày 27 thì của Bn phía trên e báo. "orderId":"XPPNYVPVGPXI"

Còn file ngày 29 này là của BN BV mới làm
"orderId":"QQTVFAMMSNCZ"
[main.js-2024-05-29.info.log.txt](https://github.com/dh-hos/dhg.hospitalprinter/files/15481631/main.js-2024-05-29.info.log.txt)

**Comment by ongtrieuhau-dh** [comment]
chạy lại workflow rồi thử lại nhé 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/f59a32e3-642e-446e-8e71-a6a5f125d8d3)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/79b440c8-61fb-4d3b-9ebf-614dea59c117)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/eb1168f5-c310-416f-8ebb-ef557310f870)

**Comment by lqbinh1987** [comment]
Đã fix
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/9c951e0e-9278-443d-a986-eea313802520)
