### ISSUE TITLE
Lỗi - Bảng kê tiền giao dịch qua thanh toán QR bị double nhiều lần

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#155]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/05/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51214`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nội Tiết**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ttntqn_052024_3`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1FItaezSwBBytTeMfyWPymMtdg6STlCJ2/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024004609` - _**MaKB**_: `2405005163` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/05/2024` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Hiện tại khi giao dịch thành công, thì dữ liệu trong bảng pay.exchanges bị nhiều dòng trùng nhau của cùng 1 giao dịch.
Như BN dưới trùng lại tới 10 lần. Nên báo cáo quản lý giao dịch số tiền bị x10 lần.

Có cas có cas không bị, nhiều giao dịch bị lỗi vậy, có khi x2, x3, x4... mà em đã test 1 số thao tác tại BV mà vẫn ko ra đc lỗi trên.
Đã có dữ liệu _pay
File log: "orderId":"ZWDIFAWYCOQO"
[main.js-2024-05-23.info.log.txt](https://github.com/dh-hos/dhg.hospitalprinter/files/15482047/main.js-2024-05-23.info.log.txt)

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/9aed643e-41d6-4d7f-adb2-cca4455e5bb8)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/99630883/d11207c5-83b3-4c57-aea0-097eb9cbab58)

**Comment by gh-dh-bot-01** [comment]
###### 📣[gh-bot-dh-hos-projects-timelines] - Nhật ký thay đổi công việc hiện tại 📣 [dataUrl](https://o-dh-002-default-rtdb.asia-southeast1.firebasedatabase.app/github-com/dh-hos/webhooks/Issues/dhg-hospitalprinter/155)

**Comment by ongtrieuhau-dh** [comment]
Theo dõi thử xem hôm nay còn bị hông nhé, nếu còn thì lấy dữ liệu mới về xử lý, còn hông bị thì hỗ trợ xóa những dòng bị trùng đi là được

**Comment by ongtrieuhau-dh** [comment]
Cái này sao rồi?

**Comment by lqbinh1987** [comment]
Hiện tại theo dõi hết hôm qua thì ko thấy tình trạng trên nữa, còn dl cũ để e hỗ trợ xóa trùng.
