### ISSUE TITLE
Lỗi - Bệnh án ngoại trú theo đợt  In xác nhận phát thuốc tại nút In Toa thuốc + Mẫu BHYT không in được số thứ tự và không hiển thị lên Tivi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#156]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **10/06/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap_sttphatthuoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `N2024015414` _**NgayKCB**_: `10/06/2024` - _**MaPhong**_: `BH-HOHAP` - _**MaDV**_: `10` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `04` - _**MaHH**_: `MaHH` - _**SoHD**_: `K41.00008/202406` - _**NgayHD**_: `10/06/2024` - _**ThangKT**_: `06` - _**NamKT**_: `2024`
BANT Theo đợt Bệnh nhân trên khi bấm nút In Toa thuốc + Mẫu BHYT không in được số thứ tự và không hiển thị lên Tivi
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/3f4d43c8-2e0e-46cc-b1de-f4c5695d29c7)

Còn bệnh nhân khám ngoại trú thì in số thứ tự và hiển thị lên TV bình thường
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/f122b27b-076a-4c6b-9ccf-b82273a7f54d)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/ec3ca1ae-23e5-4450-9778-1cf74cb3aeb6)

**Comment by ongtrieuhau-dh** [comment]
Chức năng hiện tại chỉ ở mức là Toa chưa in thôi nhé

**Comment by hvtuan1987** [comment]
@ongtrieuhau Anh có thể nói rõ hơn dùm em tí á !
BANT này lúc đầu chưa in á: Khi em bấm nút In Toa thuốc + mẫu BHYT thay vì in giống khám ngoại trú thường nhưng không in được số thứ tự và không hiển thị trên danh sách phát thuốc !

**Comment by ongtrieuhau-dh** [comment]
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/fcebd8e5-9645-4565-b1af-3acd302f210b)

**Comment by hvtuan1987** [comment]
Vì toa chưa in thì hong thấy những bệnh nhân có Bệnh án ngoại trú theo đợt để bấm xác nhận á.
Hiện tại phải chọn ngay check Bệnh án ngoại trú mới thấy bệnh nhân có bệnh án theo đợt á
Bệnh viện xác nhận từ lúc triển khai vẫn in STT và hiển thị lên TV bình thường á !

**Comment by ongtrieuhau-dh** [comment]
Nhờ @hvtuan1987 cung cấp bảng nào thực hiện được chức năng này nhé

**Comment by hvtuan1987** [comment]
@ongtrieuhau Chổ này đã xong rồi á. Do không check chổ In số thứ tự và phân khu trên phiếu KCB 6556
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/2b94d712-117f-4c3e-b262-1e82b85ddc87)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/34dd7b2e-4802-413e-b8a4-c25aa803774f)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272364/43d39e1f-fb7c-4996-991f-f031dbef8d3e)
