### ISSUE TITLE
Lỗi - TRÀ CÚ MẤT THÔNG TIN STT PHÁT THUỐC TRÊN BẢNG KÊ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprinter#159]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT HUYỆN TRÀ CÚ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbtracu0107`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/YJRptveDX)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024020798` - _**MaKB**_: `2407000720` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Chức năng in STT lên bảng kê cho Trà Cú trên printer 01/07 không thể hiện lên bảng kê

- Đã cấu hình và cấp số được trên Ordinal
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/0d71608a-dd98-46ff-ba5a-13d6300e92e5)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/ae383fa1-0892-43c7-a617-6c68d087db41)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/e4f30819-5efd-4df0-b9fe-1db3af4148e8)

- Đã cấu hình phân khu để lấy STT
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/c360d032-1f38-4fe8-afd1-7278ee0dcac6)

- Para vẫn để như cũ 
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/bb28198c-07f5-498b-986c-ff1538ac25fe)

- Khi in ra không thể hiện
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/292a6f49-ce04-41fe-b543-796c37cb0e60)

hiện tại trả về bảng cũ sẽ lỗi cấu trúc nên anh @ongtrieuhau check dùm em sớm nhé

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @ongtrieuhau
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  ⌛ Thời gian hoàn thành dự kiến: **2024-07-10**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by ongtrieuhau-dh** [comment]
**Hiện thấy các thông tin chưa khớp, kiểm tra lại giúp CODE nhé** 

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/155862740/5a488b3f-eea1-4e28-a4c0-f527387bb55e)

**Comment by nqhoa1005** [comment]
Em đóng Git này để mở lại lỗi tại Ordinal insert sai makb vào monitor

![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/130281806/304260a1-c809-44cd-91e6-7c057c33babe)
