### ISSUE TITLE
Lỗi - khi in phiếu 01KCB tại Printer

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#160]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **23/07/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Phước Long Bạc Liêu**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbphuoclong_052024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/0Di2OIihZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010364` - _**MaKB**_: `2405011847` - _**MaBA**_: `MaBA` _**NgayKCB**_: `23/07/2024` - _**MaPhong**_: `00` - _**MaDV**_: `02` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

Khi in phiếu 01BCK tại Printer  xuất hiện lỗi như hình dưới
![image](https://github.com/user-attachments/assets/52f01834-cceb-4205-abc2-75df0282d29c)

Chi tiết lỗi
Error [0]Message: Lỗi code [OTH.Adapter.HosBHXH.AGiamDinh.loadData].

Error [0]HResult: -2146233088
Error [0]Source: OTH.Adapter
Error [0]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV(String pThemoi, EventArgs e, outtv exportTV)
Error [0]TargetSite: Void loadData()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.Couldn't store <System.Byte[]> in chidinhcls_oid Column.  Expected type is Int32.
Error [1]HResult: -2147024809
Error [1]Source: OTH
Error [1]StackTrace:    at OTH.ClsPostgres.CmdPgSQL.GetDataTable(String sSQL)
   at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
Error [1]TargetSite: System.Data.DataTable GetDataTable(System.String)

Error [2]=== INNER EXCEPTION ===
Error [2]Message: Unable to cast object of type 'System.Byte[]' to type 'System.IConvertible'.
Error [2]HResult: -2147467262
Error [2]Source: System.Data
Error [2]StackTrace:    at System.Data.Common.Int32Storage.Set(Int32 record, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
Error [2]TargetSite: Void Set(Int32, System.Object)

**Comment by ongtrieuhau-dh** [comment]
Lỗi này ở bệnh viện có bị hông? Còn máy chủ công ty đang lỗi OID rồi, chỗ @le-an-87  đang cài thêm. @hvtuan1987

**Comment by hvtuan1987** [comment]
Bệnh viện thì chưa thấy báo á !  tại em test để kiểm tra các bảng khác á !

**Comment by hvtuan1987** [comment]
Do đơn vị chưa phát sinh lỗi như hiện tạinên tạm thời đóng github
