### ISSUE TITLE
Lỗi - Printer không in được bảng kê 01KCB 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#163]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **06/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap_khongindckcb`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/RujC3l1rz)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022082131` - _**MaKB**_: `2408007024` - _**MaBA**_: `MaBA` _**NgayKCB**_: `06/08/2024` - _**MaPhong**_: `BH-NOI1` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `04` - _**MaHH**_: `` - _**SoHD**_: `K01.00204/202408` - _**NgayHD**_: `06/08/2024` - _**ThangKT**_: `08` - _**NamKT**_: `2024`

Bệnh nhân có Toa ở Phòng khám BH-NOI1 (Mã đv: 10 Khoa khám bệnh ) sau đó Bác sĩ chuyển bệnh nhân sang phòng khám BH-YHCT của Khoa YHCT (Mã đv 02) Khoa này xử trí Bệnh án ngoại trú Theo ngày.

Lúc này xuống Printer in phiếu KCB  Xuất hiện Hộp thoại thông báo như hình dưới , bấm Đồng ý và không xuất hiện thông báo gì thêm. Khi xem lại bệnh nhân ở trạng thái chưa in
Ghi chú thêm: bệnh nhân chưa phát sinh % cùng chi trả nhưng hộp thoại thông báo số tiền bệnh nhân phải trả -5% của Tổng tiền BHYT 
![image](https://github.com/user-attachments/assets/6e38d581-bf7c-40e9-8f00-bc4ab6f8b73c)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-09**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0810.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408100-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408100-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408100-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Lỗi - Printer không in được bảng kê 01KCB![](https://i.imgur.com/5utpQkn.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/163

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @hvtuan1987 @lqbinh1987 @nghivanbi

**Comment by hvtuan1987** [comment]
Đã in được bảng kê !
![image](https://github.com/user-attachments/assets/27035ee6-c0e1-4eea-b0de-f7e27a70b313)
