### ISSUE TITLE
Lỗi - Không in phiếu 6556 khi chưa phát sinh cùng chi trả.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#164]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **11/08/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_govap_koinphieu_bhytkothanh`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/ke71kuSsl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2408002354` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/08/2024` - _**MaPhong**_: `BH-HOHAP` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN có vừa có thuốc BHYT không thanh, vừa có thuốc BHYT thanh toán, chung 1 kho, phần thuốc BHYT chưa phát sinh cùng chi trả, chỉ thu tiền đối với thuốc BHYT KHÔNG THANH, thu rồi nhưng khi in phiếu thì printer vẫn báo lỗi như hình dưới.
![image](https://github.com/user-attachments/assets/b3c76a05-bd1f-4c20-baa1-aa04520679c8)

**Lưu ý nếu có phát sinh tiền cùng chi trả, Fees thu tiền hết cả BHYT thanh và không thanh thì Printer in được, nhưng sau khi in phiếu xong xuất hiện lỗi như hình dưới, và danh sách BN có màu vàng, không phải màu hồng như trước đây**

Error [0]Message: Lỗi xảy ra tại [Name:Void OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished(),Assembly:OTH.Adapter.dll,Version: Version=1.24.811.1].
Error [0]HResult: -2146233088
Error [0]Source: OTH.Adapter
Error [0]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintFinish(Boolean IsUpdateChandoanXml)
   at OTH.XForms.HosPrinter.BKChiPhiKCB6556.PrintByOption(Form parentForm, Boolean IsUpdateChandoanXml, Int16 forceCopies)
   at HosPrinter.Classes.ClsHauThem.ExportXMLAndPrint6556(String xml_MaBN, String xml_MaKB, Form parentForm, GridEX dgCls, String strTKLapToa, String strTenPK, Int32 solanin, String strTKNhapBenh, GridEX dgThuoc, v_FormInPhieu01 vFormInPhieu01, String strTKLapToa_Manv_PhuongNam, QuayPhatThuoc quayPhatThuoc)
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV_UpdatePSDANGKY_THEN_EXPORT_PRINT6556(ToathuocInfo toathuocInfo)
   at HosPrinter.Forms.FrmInPhieuKCB.InMauBHYT01BV(String pThemoi, EventArgs e, outtv exportTV)
Error [0]TargetSite: Void Print01Finished()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: Lỗi xảy ra tại [Name:Void OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130(),Assembly:OTH.Adapter.dll,Version: Version=1.24.811.1].
Error [1]HResult: -2146233088
Error [1]Source: OTH.Adapter
Error [1]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130()
   at OTH.Adapter.HosBHXH.AGiamDinh.Print01Finished()
Error [1]TargetSite: Void SaveXML130()

Error [2]=== EXCEPTION POSTGRESQL===
[BaseMessage]:invalid input syntax for type numeric: ""

[ErrorSql]: INSERT INTO xml130.bang3(ma_lk,stt,ma_dich_vu,ma_pttt_qt,ma_vat_tu,ma_nhom,goi_vtyt,ten_vat_tu,ten_dich_vu,ma_xang_dau,don_vi_tinh,pham_vi,so_luong,don_gia_bv,don_gia_bh,tt_thau,tyle_tt_dv,tyle_tt_bh,thanh_tien_bv,thanh_tien_bh,t_trantt,muc_huong,t_nguonkhac_nsnn,t_nguonkhac_vtnn,t_nguonkhac_vttn,t_nguonkhac_cl,t_nguonkhac,t_bntt,t_bncct,t_bhtt,ma_khoa,ma_giuong,ma_bac_si,nguoi_thuc_hien,ma_benh,ma_benh_yhct,ngay_yl,ngay_th_yl,ngay_kq,ma_pttt,vet_thuong_tp,pp_vo_cam,vi_tri_th_dvkt,ma_may,ma_hieu_sp,tai_su_dung,du_phong,mabn,makb,mahh,sohd,macls,ngaykcb) VALUES ( '79035_2024_08_2024000001_2408002354' , 1 , '02.1897' , '' , '' , '13' , '' , '' , 'Khám Nội' , '' , 'lần' , 1 , 1.00 , 37500.00 , 37500.00 , '' , '100' , '100' , 37500.00 , 37500.00 , '' , 100 , 0 , 0 , 0 , 0 , 0 , 0.00 , 0.00 , 37500.00 , 'K01' , '' , '000000' , '' , 'A00' , '' , '202408111811' , '202408111811' , '' , '1' , '' , '4' , '' , '' , '' , '' , '' , '2024000001' , '2408002354' , '' , '' , 'KB20' ,  CAST(TO_TIMESTAMP('11/08/2024 18:11:11','DD/MM/YYYY HH24:MI:SS') AS TIMESTAMP WITHOUT TIME ZONE)  );

[Routine]:set_var_from_str

[Detail]:

Error [2]=== INNER EXCEPTION ===
Error [2]Message: ERROR: 22P02: invalid input syntax for type numeric: ""
Error [2]HResult: -2147467259
Error [2]Source: OTH
Error [2]StackTrace:    at OTH.ClsPostgres.CmdPgSQL.ExecuteSQLOnTrans(String sSQL, NpgsqlTransaction trans)
   at OTH.Adapter.HosBHXH.AGiamDinh.SaveXML130()
Error [2]TargetSite: Void ExecuteSQLOnTrans(System.String, Npgsql.NpgsqlTransaction)

![image](https://github.com/user-attachments/assets/184b7997-bf1d-4fb2-be67-b89ca9cd3db7)
![image](https://github.com/user-attachments/assets/ad1782a5-ecb7-441a-a477-9c0df74696e1)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0812.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408120-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408120-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408120-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_Lỗi - Không in phiếu 6556 khi chưa phát sinh cùng chi trả._** ![](https://i.imgur.com/gu2LQMt.png) ![](https://i.imgur.com/0fdzRDS.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/164

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
Lỗi trên đã in được, nhưng nếu có phát sinh chi phí BHYT và BHYT không thanh thì cảnh báo sai số tiền, sai cả 2 trường hợp BN được hỗ trợ ngân sách (**dmchucai.ptngansach KHÁC 0** VÀ **psdangly.mahongheo KHÁC rỗng**) và không được hỗ trợ ngân sách



[Link data 2 BN](https://gofile.me/78TQg/3NbxGD9q2)

### **Không được hỗ trợ ngân sách.**
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000002` - _**MaKB**_: `2408002355` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/08/2024` - _**MaPhong**_: `BH-HOHAP` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
![image](https://github.com/user-attachments/assets/5df94159-c691-40d4-b1de-babb5fb3f94f)
![image](https://github.com/user-attachments/assets/e3497ff8-de43-4cfb-9ba5-ac5d1c9c103b)

### **Được hỗ trợ ngân sách.**
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024000001` - _**MaKB**_: `2408002354` - _**MaBA**_: `MaBA` _**NgayKCB**_: `11/08/2024` - _**MaPhong**_: `BH-HOHAP` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2024`
![image](https://github.com/user-attachments/assets/f230eee5-00d2-4b1d-93fc-055b66f2c462)
![image](https://github.com/user-attachments/assets/ad72dc40-76a8-484a-9d38-66a3296c6808)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-20**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.0818.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408180-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408180-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32408180-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_Lỗi - Không in phiếu 6556 khi chưa phát sinh cùng chi trả._**

- 🐛: Tính sai chi phí đối với PHAM_VI=2 ![](https://i.imgur.com/q6QjHnw.png) ![](https://i.imgur.com/KhNIfU3.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/164

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi
![image](https://github.com/user-attachments/assets/8002641c-6345-4fd3-b10d-aadfbd5e19b5)
