### ISSUE TITLE
Lỗi - GHI NHẬN SAI THÁNG QUYẾT TOÁN KHI IN BẢNG KÊ BỆNH NHÂN THÁNG CŨ

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprinter#172]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_thanhtri_full_24092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/Oi8YIgvrM)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Trường hợp thao tác người dùng in sót các bệnh nhân của tháng cũ khi qua tháng kế toán mới in bổ sung thì dữ liệu mặc định ghi nhận tháng quyết toán là tháng mới 
![image](https://github.com/user-attachments/assets/4c8b44d5-00df-4c54-9894-ec14682820a3)
![image](https://github.com/user-attachments/assets/a821a2da-c536-4dcc-97f4-f5022c97121f)
![image](https://github.com/user-attachments/assets/6b8445f8-2d5a-45fa-9e7b-f1b877a4ef23)

đồng thời tháng quyết toán trong malk cũng là tháng mới 
![image](https://github.com/user-attachments/assets/6ec18d2c-58ba-43ec-ba84-c5be5bca0338)
![image](https://github.com/user-attachments/assets/660c93a5-43f0-42e0-ae32-d824f9fb1d3a)

khi mở khoá chứng từ thì vẫn giữ lại tháng quyết toán nên in lại vẫn sẽ sinh ra malk tháng mới.
![image](https://github.com/user-attachments/assets/8471190a-f899-4e8e-8ffa-9f5d546f5f74)

- Hỗ trợ ghi nhận đúng tháng quyết toán khi in bệnh nhân tháng cũ.
- Hỗ trợ người dùng cập nhật lại tháng quyết toán và malk đúng do dữ liệu tháng cũ nhiều đơn vị vẫn đang sai.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.1010.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410103-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410103-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32410103-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - GHI NHẬN SAI THÁNG QUYẾT TOÁN KHI IN BẢNG KÊ BỆNH NHÂN THÁNG CŨ_**

- 🐛: Chỉnh lỗi liên quan tới xuất XML4750 trên báo cáo Admin, Reports ![](https://i.imgur.com/1DKpyWX.png) ![](https://i.imgur.com/bn684Rf.png)![](https://i.imgur.com/ryo2V1I.png)![](https://i.imgur.com/NUJNtfn.png)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/172

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã đúng thông tin malk khi in lại

✅ BANT ngày
- Ban đầu
![image](https://github.com/user-attachments/assets/b537c6ad-695b-4f51-ba97-a3948413990a)
![image](https://github.com/user-attachments/assets/70e1e3e6-3088-4231-8b0e-f6e71497b34d)
![image](https://github.com/user-attachments/assets/9d240391-9c8d-4d1f-be6b-031b9531be74)

- Mở khoá và in lại
![image](https://github.com/user-attachments/assets/34cfc45b-773d-41fa-9ce5-7ac0d4aba6f3)
![image](https://github.com/user-attachments/assets/6d1448f8-9b96-45d0-9dd0-382263948433)

![image](https://github.com/user-attachments/assets/19d43e19-cb7e-4f15-8726-edf1e431f7f1)

---
Trường hợp tháng cũ chưa in lần nào
khi in lại
![image](https://github.com/user-attachments/assets/1dfbe61c-f803-4df6-9659-56e1df044cbb)
![image](https://github.com/user-attachments/assets/c3385fe5-8f4a-4b7a-a2f3-ef911f876e7e)
![image](https://github.com/user-attachments/assets/40064090-9fe3-4940-886b-dbb299e72e45)


✅ Ngoại trú



---
✳️ Lần test :1
