### ISSUE TITLE
Lỗi - Bảng kê 6556 hiển thị chi phí ngoài BHYT

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#175]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **14/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77156`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Phúc Gia Khang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_pkphucgiakhang_chiphingoaibhyt`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/JxCsxMe8S)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024010271` - _**MaKB**_: `2410001710` - _**MaBA**_: `MaBA` _**NgayKCB**_: `14/10/2024` - _**MaPhong**_: `KB9` - _**MaDV**_: `02.03` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tùy chọn như cấu hình, nhưng khi in mẫu 6556 vẫn hiên thị chi phí ngoài BHYT.
![image](https://github.com/user-attachments/assets/9eba155b-6c15-4c81-9c94-62393bd54799)

Lưu ý là bản cũ thì vẫn in được, bản cũ không thể hiện chi phí ngoài BHYT trên cùng trang chi phí BHYT.
![image](https://github.com/user-attachments/assets/0628c164-50b1-498c-aadf-04ef9e498bfe)

Nếu tùy chọn tách chi phí BHYT và ngoài BHYT trên 2 trang in thi phần mềm vẫn in ra 1 bản chi phí ngoài BHYT mặc dù có tùy chọn số bản in là 0 cho trang in chi phí ngoài BHYT.

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-10-21**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @lqbinh1987 
- ***Phiên bản mới nhất thấy không gặp vấn đề trên đề cập***: ![](https://i.imgur.com/68V4D7E.png) ![](https://i.imgur.com/5SkmIxJ.png) ![](https://i.imgur.com/1ILIInd.png)

**Comment by lqbinh1987** [comment]
💡KIỂM TRA SẢN PHẨM💡
***
Mô tả lỗi:
Đã cấu hình in tách phiếu, nhưng cũng có cấu hình số bản in phiếu không BHYT là 0, nhưng hi in mẫu BHYT xong, phần mềm vẫn in ra bảng kê không BHYT, nhiều đơn vị không cần in mẫu này.
![image](https://github.com/user-attachments/assets/2e7b53a0-a6e6-4c4d-a751-e9a17e9e4b8b)
![image](https://github.com/user-attachments/assets/07afa746-b90b-4c21-b173-5a9db2610a38)
![image](https://github.com/user-attachments/assets/ce6f0d2b-2b30-4323-af87-ae030725099a)
![image](https://github.com/user-attachments/assets/65709454-bd1d-47f1-bf95-e6b04ca291e7)

***
Thông tin bệnh nhân(nếu có)
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `Tên data`
- ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link)
-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`

***
❌ Không thể tiếp tục kiểm tra sản phẩm, **tạm dừng kiểm tra.**

## - Test lần 1

**Comment by lqbinh1987** [comment]
🐛  Đã fix lỗi
![image](https://github.com/user-attachments/assets/e33b4d36-71a0-40bd-9365-afb21207fa08)
![image](https://github.com/user-attachments/assets/959426d9-58f0-4798-af31-3860d757cdcc)
