### ISSUE TITLE
Lỗi - PHÁT SINH LỖI KHI IN BẢNG KÊ NGOẠI TRÚ 

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprinter#176]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **15/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV ĐKTP CẦN THƠ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dktpct_102024092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/4VVaBufOZ)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024068406` - _**MaKB**_: `2410009119` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `005` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Phát sinh lỗi khi in bảng kê, sau khi đóng vẫn in được ra bảng kê nhưng không có XML
![image](https://github.com/user-attachments/assets/e42d94f3-61f8-4602-8704-14c3d19592fe)
![image](https://github.com/user-attachments/assets/667a2266-b5bb-4904-b3be-cc4521da2c9c)
![image](https://github.com/user-attachments/assets/1a5c537a-aee4-44ee-a000-90a23921c69c)

In lần 2 thì không báo lỗi có XML bình thường
![image](https://github.com/user-attachments/assets/c9073523-61ea-45ad-9ee8-23d8bedf9120)

---
dữ liệu đã có nhận sẳn 1 ca để test
   > _**MaBN**_: `2024068412` - _**MaKB**_: `2410009120` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `005` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

**Comment by ongtrieuhau-dh** [comment]
## <sub><sub>☑️ Đã tiếp nhận</sub></sub>

- ⌛ Thời gian hoàn thành dự kiến: **2024-10-21**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1015.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410150-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410150-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410150-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - PHÁT SINH LỖI KHI IN BẢNG KÊ NGOẠI TRÚ _**

- 🐛: Chỉnh lỗi khi in phiếu 01. ![](https://i.imgur.com/sZ0el9b.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/176

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
❌ **CHƯA ĐẠT YÊU CẦU** ❌ 
- ❗❗ Đã cập nhật bản mới nhận vào ca mới để thử thì vẫn bị lỗi tương tự
https://github.com/user-attachments/assets/9863007f-a6d1-40d5-9a36-169948f3d5dd

---
- ✳️ Lần test : 1
- ❗❗ Dừng test các chức năng liên quan.

**Comment by nqhoa1005** [comment]
Em đã nhận ca mới để debug
![image](https://github.com/user-attachments/assets/d90708a6-7dc3-4379-913b-1c21b96f9549)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalPrinter.exe v.3.24.1015.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410151-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410151-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalPrinterexe%2F32410151-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Lỗi - PHÁT SINH LỖI KHI IN BẢNG KÊ NGOẠI TRÚ _**

- 🐛: Chỉnh lỗi khi in phiếu 01. ![](https://i.imgur.com/vPeDCMf.gif)

- ☑: https://github.com/dh-hos/dhg.hospitalprinter/issues/176

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalPrinter.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nqhoa1005** [comment]
✅ HOÀN THÀNH
👉 Đã fix không còn phát sinh lỗi và xuất XML bình thường

![image](https://github.com/user-attachments/assets/80615f76-76c9-42f5-9c64-5cbdc9c0387a)
![image](https://github.com/user-attachments/assets/2e3a7720-f3d7-444d-bfd2-adb794158807)
![image](https://github.com/user-attachments/assets/b59979d4-511d-42c2-96ee-ae3b53c6565d)
---
✳️ Lần test : 2
