### ISSUE TITLE
Lỗi - CẬP NHẬT LẠI TRÁI TUYẾN CHO BỆNH NHÂN => XML1.MA_DOITUONG_KCB = 9

### ISSUE THREAD

**Issue by nqhoa1005** [dh-hos/dhg.hospitalprinter#177]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **NGUYỄN QUỐC HOÀ**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `94006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK H.THẠNH TRỊ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `hoa_dbthanhtri_102024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/BY0O0jHXm)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024003165` - _**MaKB**_: `2410002873` - _**MaBA**_: `MaBA` _**NgayKCB**_: `08/10/2024` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `10` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Tại chức năng chỉnh thông tin của Printer khi cập nhật lại trái tuyến cho bệnh nhân thì giá trị XML1.MA_DOITUONG_KCB = 9 không cập nhật lại được .
- Mở khoá chứng từ và chỉnh thông tin lại sang trái tuyến
![image](https://github.com/user-attachments/assets/a453a5be-25a8-42d0-ac46-02d68a3f4145)

Xuất 4750 sau khi in lại bảng kê
![image](https://github.com/user-attachments/assets/aa9307e9-56b6-46d5-a045-1186200ea0e1)

Cập nhật chi phí lại so với 4210
![image](https://github.com/user-attachments/assets/a7edd99a-7b41-4eaa-aa27-bed91764b711)
👉 sau khi cập nhật xuất lại thì xuất 4750 và 130  XML1.MA_DOITUONG_KCB vẫn = 9
![image](https://github.com/user-attachments/assets/6d3ca80e-774a-478b-bc66-6113f2514c93)
![image](https://github.com/user-attachments/assets/47e7c9ca-c066-41b2-ba51-281349108c46)

✴️ Fix dùm em Cập nhật tuyến theo [Thay đổi thao tác xác định tuyến](https://github.com/dh-hos/To_Lap_Trinh/issues/706) để lấy đúng thông tin  XML1.MA_DOITUONG_KCB

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Mô tả rõ hơn thông tin lỗi cái nhé, và khi trạng thái trái tuyến như vậy thì mã đối tượng mong muốn của Khách hàng là như thế nào.

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
✳️Chổ này theo [mô tả](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md) thì nếu tuyenbv = 2 thì nếu chỉnh trái tuyến thì psdangky.tuyen = 0 và psdangky.tuyenxml = 1 thì mới ra đúng XML1.MA_DOITUONG_KCB anh @ongtrieuhau 
![image](https://github.com/user-attachments/assets/499ea68a-f97e-47ec-ba13-831b11b42e90)

👉 thao tác cập nhật lại trái tuyến ở Printer update luôn psdangky.tuyen = 1 nên xảy ra trường hợp này á anh
![image](https://github.com/user-attachments/assets/832b0148-4f3e-429a-84f2-74491c8a1b04)

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Nghĩa là chỉnh từ `Trái tuyến` sang `Cùng tuyến` vẫn không lấy đúng mã đối tượng đúng không?

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
✳️ngược lại anh @ongtrieuhau , mấy ca lỡ chọn đúng tuyến rồi khi chỉnh lại trái tuyến thì bị trường hợp này

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @nqhoa1005  </sub>

- Vậy nếu ` Trái tuyến` thì giá trị nào phù hợp

**Comment by nqhoa1005** [comment]
❗❗ **TRAO ĐỔI** ❗❗
✳️Xác nhận lại chổ này là nếu ban đầu nhận bệnh xác định đúng đối tượng trái tuyến thì giá trị psdangky.tuyen = 0 và psdangky.tuyenxml = 1 => Đúng => Khi xuất XML thì XML1.MA_DOITUONG_KCB = 3.3 

❌ Các trường hợp em test lại khi người dùng chọn Đúng tuyến đối với thẻ ngoài tỉnh/tuyến trên thì khi chỉnh lại về trái tuyến tại Printer thì **psdangky.tuyen = 1** và psdangky.tuyenxml = 1 nên XML1.MA_DOITUONG_KCB = 9

👉 Phát sinh lỗi khi chọn lại trái tuyến tại Printer thì update luôn psdangky.tuyen = 1 => sai 
Lúc này khi in lại bảng kê thì XML1 sẽ lấy MA_DOITUONG_KCB = 9
---

**Comment by ongtrieuhau-dh** [comment]
## <sub><sub>☑️ Đã tiếp nhận</sub></sub>

- ⌛ Thời gian hoàn thành dự kiến: **2024-10-28**

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by nqhoa1005** [comment]
Đóng Git mô tả lại rõ ràng theo https://github.com/dh-hos/dhg.hospitalprinter/issues/178 để đúng mục đích cần fix
