### ISSUE TITLE
Lỗi - PRINTER IN PHIẾU 01 KHÔNG HIỂN THỊ HỌ TÊN NGƯỜI LẬP BẢNG KÊ

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprinter#179]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ĐỨC**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **30/10/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92085`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tâm Thần Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_tamthan`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/LSsPsKCCS

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024008613` - _**MaKB**_: `2410002618` -_**NgayKCB**_: `30/10/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2024`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

**Khi in phiếu KCB Lần 1 không hiển thị Họ tên người lập bảng kê**
**Khi in phiếu KCB Lần 2 Có hiển thị Họ tên người lập bảng kê**

![image](https://github.com/user-attachments/assets/970dfeb9-c273-4838-843d-0d88d1b7e5aa)

![image](https://github.com/user-attachments/assets/906775f8-93cd-4b86-9474-3e9914d6161e)

Test trên Printer bản 3.24.1022.1

![image](https://github.com/user-attachments/assets/8becf68e-400b-42b6-adba-8dbbb9a0a294)

Video thao tác: https://gofile.me/78TQg/Pi2tIOzxS

**Comment by le-an-87** [comment]
### ❓ TRAO ĐỔI ❓ 
coi lỗi này giùm tổ em anh @nghivanbi @onghaup 
***

**Comment by onghaup** [comment]
### <sub>✔️ Tiếp nhận và Thực hiện công việc<sup><sup>[HD.05]</sup></sup></sub>

---

- **📘 Mô tả thực hiện:** **_Theo luồng công việc này._**

- **⏳ Thời gian hoàn thành:** **_2024-11-18_**
