### ISSUE TITLE
Test chức năng [In toa thuốc và Phiếu BHYT]

### ISSUE THREAD

**Issue by o-ngtrieuhau861gmailcom** [dh-hos/dhg.hospitalprinter#18]
Bản mới: https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/d10ab34a16953bfa6ea79a3e1aa851de02521c31
Nội dung thay đổi: chỉnh code toàn bộ lại chức năng In toa thuốc và phiếu BHYT, đối với cả nhà thuốc và khoa dược
Test kỹ lại các chức năng của nút in này so với bản cũ:

- Các trang in: toa thuốc, phiếu 01, phiếu phụ thu, phiếu thu...
- Qui trình cập nhật khi thực hiện in phiếu: khóa toa, đánh dấu đã in BHYT, chứng từ thuốc, cận lâm sàng
- Thực hiện trên nhiều dữ liệu của các bệnh viện khác nhau

Ghi chú: hiện đang mở form cũ trong phần cấu hình hệ thống, có thể chạy cùng lúc 2 form để xem sự thay đổi.

**Comment by nghibi** [comment]
@le-an-87 hỗ trợ cái này nha.

**Comment by BlueTea92** [comment]
![image](https://user-images.githubusercontent.com/97272332/161657851-33ad7c80-4108-4125-b92b-3016eb8c089c.png)
- Thông báo lỗi ngoài định xuất khi in bảng kê

**Comment by BlueTea92** [comment]
- bệnh nhân ngoại trú không lấy thuốc
- mở khoá chứng từ -> phục hồi toa không lấy thuốc
- > chỉnh được toa thuốc
- > không chỉnh được chẩn đoán và chỉ định CLS 
=> do cột psdangky.dain và chidinhcls.dain không phục hồi lại =0 (#0)
![image](https://user-images.githubusercontent.com/97272332/161882437-7227447d-a414-476e-821e-90069eddbf67.png)
![image](https://user-images.githubusercontent.com/97272332/161882466-f9889076-0411-4e41-854e-44972f0a4e87.png)

**Comment by BlueTea92** [comment]
- Vào in phiếu KCB -> Chỉnh thông tin -> bấm Hiệu chỉnh -> bấm Bỏ qua
- -> phần mềm báo lỗi
![image](https://user-images.githubusercontent.com/97272332/161885678-b341d639-bf9f-41f7-851e-32ff93d53f62.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cho anh xin thông tin dữ liệu test mấy phần này nhé.

**Comment by BlueTea92** [comment]
data nha anh: 
tra_giarai_banttoacu

**Comment by o-ngtrieuhau861gmailcom** [comment]
> ![image](https://user-images.githubusercontent.com/97272332/161657851-33ad7c80-4108-4125-b92b-3016eb8c089c.png)
> 
> * Thông báo lỗi ngoài định xuất khi in bảng kê

Mở rộng thông báo lỗi này giùm anh để anh báo lại dll nhé

**Comment by o-ngtrieuhau861gmailcom** [comment]
> * bệnh nhân ngoại trú không lấy thuốc, không ký tên
> * mở khoá chứng từ -> phục hồi toa không lấy thuốc
> * -> chỉnh được toa thuốc
> * -> không chỉnh được chẩn đoán và chỉ định CLS
>   => do cột psdangky.dain và chidinhcls.dain không phục hồi lại =0 (#0)
>   ![image](https://user-images.githubusercontent.com/97272332/161882437-7227447d-a414-476e-821e-90069eddbf67.png)
>   ![image](https://user-images.githubusercontent.com/97272332/161882466-f9889076-0411-4e41-854e-44972f0a4e87.png)

Cho anh xin thông tin dữ liệu đang test nhé

**Comment by o-ngtrieuhau861gmailcom** [comment]
> * bệnh nhân ngoại trú không lấy thuốc, không ký tên
> * mở khoá chứng từ -> phục hồi toa không lấy thuốc
> * -> chỉnh được toa thuốc
> * -> không chỉnh được chẩn đoán và chỉ định CLS
>   => do cột psdangky.dain và chidinhcls.dain không phục hồi lại =0 (#0)
>   ![image](https://user-images.githubusercontent.com/97272332/161882437-7227447d-a414-476e-821e-90069eddbf67.png)
>   ![image](https://user-images.githubusercontent.com/97272332/161882466-f9889076-0411-4e41-854e-44972f0a4e87.png)

không chỉnh được cận lâm sàng thì báo với module Prescription nhé, vì khi phục hồi toa hiện tại chỉ cập nhật lại trong khambenh thôi, không đá đọng tới psdangky nhé

**Comment by BlueTea92** [comment]
> 

Phiên bản :2022.04.01.101148AM
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at Npgsql.NpgsqlCommand.CheckConnectionState()
   at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb)
   at Npgsql.NpgsqlCommand.ExecuteScalar()
   at LibraryApp.NpgsqlHelper.ExecuteScalar(NpgsqlConnection connection, CommandType commandType, String commandText, NpgsqlParameter[] commandParameters)
   at DH2.Xml.checkMaCC(String macc)
   at DH2.Xml.UpdateDinhSuat(String mabn, String makb, String maba, String macc, String maicd, String maicdp, Decimal tongtienbv, Decimal tongtienbh)
![image](https://user-images.githubusercontent.com/97272332/162378839-d16f25a4-c8fd-447a-9b25-f8e7880f4474.png)
- data:  tra_giarai_banttoacu
- bệnh nhân ngày 06/04

**Comment by BlueTea92** [comment]
> không chỉnh được cận lâm sàng thì báo với module Prescription nhé, vì khi phục hồi toa hiện tại chỉ cập nhật lại trong khambenh thôi, không đá đọng tới psdangky nhé

- ok anh

**Comment by o-ngtrieuhau861gmailcom** [comment]
> > 
> 
> Phiên bản :2022.04.01.101148AM System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first. at Npgsql.NpgsqlCommand.CheckConnectionState() at Npgsql.NpgsqlCommand.GetReader(CommandBehavior cb) at Npgsql.NpgsqlCommand.ExecuteScalar() at LibraryApp.NpgsqlHelper.ExecuteScalar(NpgsqlConnection connection, CommandType commandType, String commandText, NpgsqlParameter[] commandParameters) at DH2.Xml.checkMaCC(String macc) at DH2.Xml.UpdateDinhSuat(String mabn, String makb, String maba, String macc, String maicd, String maicdp, Decimal tongtienbv, Decimal tongtienbh) ![image](https://user-images.githubusercontent.com/97272332/162378839-d16f25a4-c8fd-447a-9b25-f8e7880f4474.png)
> 
> * data:  tra_giarai_banttoacu
> * bệnh nhân ngày 06/04

Cập nhật tại đây 6dde3670603eb46d6f343d0a1321609c1323caa6

**Comment by nghibi** [comment]
DLL luôn chưa?
