### ISSUE TITLE
Bỏ không load toa không tính phí, không in trên phiếu in nhiệt

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalprinter#19]
![image](https://user-images.githubusercontent.com/91751241/167528569-1a9e4015-3d60-427b-8b1c-97ee03afd2ef.png)
![image](https://user-images.githubusercontent.com/91751241/167528729-a7321077-5870-4913-a7af-642f9794124e.png)
![image](https://user-images.githubusercontent.com/91751241/167528821-62ce96b9-eedb-4a58-a585-d8e9891d4fbd.png)

data: bi_bvq122022043944_2205003407

**Comment by o-ngtrieuhau861gmailcom** [comment]
Kiểm tra lại tham số này nhé **maubhyttoavt**

**Comment by nghibi** [comment]
- Load toa vật tư thì đúng rồi nhưng bỏ toa vật tư không tính phí ra.
- BV yêu cầu bỏ trên phiếu in nhiệt (vì thuốc này đã trọn gói trong cls rồi) không có phát cho bệnh nhân.
![image](https://user-images.githubusercontent.com/91751241/167542892-d09a4a17-caed-4ef6-a2d3-1f0145059845.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Xin lại dữ liệu này để test chức năng, hiện tại hông thấy dữ liệu bi_bvq122022043944_2205003407 trên hệ thống

**Comment by lqbinh1987** [comment]
Tranh thủ dùm em chổ này lun nhe anh Hậu. E đã tạo lại dl rồi, thống tin dl như trên.

**Comment by o-ngtrieuhau861gmailcom** [comment]
Dữ liệu lại không thấy bệnh nhân như hình báo nhé @lqbinh1987 , 2205003588

**Comment by lqbinh1987** [comment]
Lấy BN này nhé anh: 2205003407

![image](https://user-images.githubusercontent.com/99630883/169962434-b239fd0e-7330-40de-bc46-13fdd602bc1d.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/4cc441e6678ebd5238fdbb095b2abfcd43c17363
Trong form cấu hình có chức năng để loại bỏ những toa vật tư không tính phí TVT1

**Comment by nghibi** [comment]
Bình check lại hỗ trợ đúng yêu cầu Q12 thì Close nha.
