### ISSUE TITLE
Bảng kê 6556 - Tính ngưỡng thanh toán

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/dhg.hospitalprinter#20]
Bảng kê 6556: đối với thuốc VTYT có áp giá thanh toán theo tỷ lệ. Bảo hiểm yêu cầu tổng chi phí để tính vượt ngưởng cùng chi trả phải tính thành tiền dựa trên tỷ lệ 100% của thuốc/VTYT chứ không lấy tỷ lệ được áp giá.

Đề nghị cung cấp dữ liệu đang dữ liệu để kiểm tra lại. @le-an-87

**Comment by le-an-87** [comment]
Em gửi tên data: an_timmach_ag_bangke_tyle
nếu tính giá có tỷ lệ thì chưa đến ngưởng thu

![image](https://user-images.githubusercontent.com/96155021/168197912-29f638d0-220a-4342-9f0a-43a2073663cf.png)

**Comment by ongtrieuhau** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalprinter/commit/ce8ea7cc4e3f508e65f91ecbd30dd74371cf573a

**Comment by le-an-87** [comment]
Đã tính cùng chi trả dự theo tổng tiền bv!
![image](https://user-images.githubusercontent.com/96155021/175438865-6e996e38-dc1b-4894-a025-32cafb666340.png)
