### ISSUE TITLE
Printer - Thông báo ngoài định xuất, không cập nhật psdangky.tongtienbv, psdangky.tongtienbh

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#22]
![image](https://user-images.githubusercontent.com/97272332/168206162-e068f4b5-b57d-4c44-8e67-d21d709f1bfe.png)
![image](https://user-images.githubusercontent.com/97272332/168206218-7c593019-d41f-4a4f-8a17-a8ff69a772f6.png)

- In bảng kê vẫn còn thông báo ngoài định xuất.
- Không cập nhật lại chi phí bảng psdangky cột tongtienbh, tongtienbv

- Data máy chủ: tra_medicmd_fees
- KCB ngày 15/05/2022, mabn: 2022044377

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái này nhờ @nghibi  kiểm tra lại giúp hiện tại đang sử dụng dll: DH2.xml.dll bản mới nhất 
![image](https://user-images.githubusercontent.com/58720300/169927781-561528b8-8e5c-4941-81f1-62fbfeb62e90.png)

**Comment by nghibi** [comment]
Cái này Hậu thử gọi riêng hàm trong DLL thôi đừng gọi lồng như hiện tại coi lỗi không?

**Comment by o-ngtrieuhau861gmailcom** [comment]
Sẽ bổ sung chức năng tắt phần in cập nhật định suất này đối với những bệnh viện nào không cần sử dụng.
![image](https://user-images.githubusercontent.com/58720300/169932600-35b5fbb2-d582-46be-91d7-3df784a20fc0.png)

**Comment by BlueTea92** [comment]
@o-ngtrieuhau861gmailcom

**Comment by BlueTea92** [comment]
@o-ngtrieuhau861gmailcom 
psdangky không có cột thanhtienbv và thanhtienbh
psdangky chỉ có cột tongtienbv và tongtienbh
anh kiểm tra lại chổ này

**Comment by o-ngtrieuhau861gmailcom** [comment]
Ok

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/407aa3c1ecb37956c8dd92fc2a0ff12ed0e387be
