### ISSUE TITLE
Lỗi In nhiệt phiếu thu nhà thuốc 

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#32]
Đã thiết kế có Họ Tên viết hoa của BN và ngày thàng nhưng lúc in ra không có, mặc dù đã load lại file, xóa para kéo vô lại nhưng cũng không được.
Số tiền bằng chữ cũng vậy.

Data: binh_nhidong, makb 2204025976, ngày 09/06

![image](https://user-images.githubusercontent.com/99630883/174202273-232f7ad9-1980-4baa-acb6-bbf06c8c943b.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/8609f169f6a6d0bf9f46f44f31cfc22a8cf69726
