### ISSUE TITLE
Lỗi: In phiếu 01 bệnh viện Quận 12

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#33]
Bệnh nhân có mã quyền lợi CN3 BH thanh toán 95% và 5% ngân sách hỗ trợ khi in bảng kê ở printer báo bệnh nhân chưa đóng tiền CCT.
in bảng kê ở Prescription hiển thị số tiền bệnh nhân cùng chi trả.
tên data: an_bv12_inbangke
makb: 2206018314

Thông tin bệnh nhân đăng ký:
![image](https://user-images.githubusercontent.com/96155021/174220515-c7ffa3c4-0996-4470-b70b-33b332f7fce4.png)

bảng kê in ở Prescription:
![image](https://user-images.githubusercontent.com/96155021/174220463-0704a41d-ad9e-4591-8c53-4803f0b401d8.png)

Cảnh báo chưa thu tiền tại printer:
![image](https://user-images.githubusercontent.com/96155021/174221947-cb5e28c8-e654-4c42-99ea-b9a886c98752.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/5ada603abd0cef8f6252b4c7b504a604a9fa3dec

**Comment by le-an-87** [comment]
bản printer 17/06/2022 V3 cũng in chưa ra được bản kê anh ơi!
![image](https://user-images.githubusercontent.com/96155021/174258002-9aa59d7b-d00e-43af-b02a-f5adcadfe6f4.png)

link data 1 bệnh nhân:
https://drive.google.com/file/d/1zGrE7FGtpmnZ0TMeEd2B3zPQTOfiiBtH/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cái này cập nhật v4 là hết nhé, v3 là chưa được đâu.

**Comment by le-an-87** [comment]
đã in được bảng kê.
