### ISSUE TITLE
Lỗi: in phiếu khám chưa bệnh - bv cái răng

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#34]
Khi in phiếu bán thuốc của đối tượng thu phí báo lỗi:
![image](https://user-images.githubusercontent.com/96155021/174269961-a0f61e50-ad93-4a72-b16c-9236dd2c0164.png)

link dữ liệu lỗi:
https://drive.google.com/file/d/14LJc3pT2Q5HuOEDkyDa9Gd3BNGMbwqV8/view?usp=sharing

**Comment by o-ngtrieuhau861gmailcom** [comment]
- Cập nhật tại https://github.com/oth-dhghospital/dhg.hospitalprinter/commit/1d04d04857e3493a99f3d2acfc8c137fa00faca9

**Comment by le-an-87** [comment]
đã fix!
