### ISSUE TITLE
Lỗi Printer vẫn cho in phiếu khi chưa thu tiền.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#35]
1. BN chỉ mới thu chênh lệch tiền DV công khám, chi phí BHYT và chênh lệch DV khác chưa thu nhưng vẫn cho in phiếu.(Hình 1 và 2)

2. BN có mã GD4(20%) có nhập mã hộ nghèo(ngân sách hỗ trợ 15%), cũng chỉ mới thu chênh lệch tiền DV công khám, chi phí BHYT và chênh lệch DV khác chưa thu nhưng vẫn cho in phiếu, vẫn có cảnh báo số tiền thu của 20%(Hình 2)
Tham số koinbndongchitra vân là 1 (Chặn không cho in bệnh nhân BHYT chưa thu đồng chi trả).(Hình 3)

Data: 2 BN -  http://www.fsend.vn/download/hEXHfvlFapY3sEeRN88-cxkTNLMHyAZW
Hình 1:
![image](https://user-images.githubusercontent.com/99630883/174434645-4faf22a8-3d23-4e4d-8a93-99f6f69952a0.png)

Hình 2:
![image](https://user-images.githubusercontent.com/99630883/174439037-647201d7-6bc0-4072-bc6c-481b56161178.png)

Hình 3:
![image](https://user-images.githubusercontent.com/99630883/174439089-65047f4f-d51b-4c66-ad7f-da760721204a.png)

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại https://github.com/dh-hos/dhg.hospitalprinter/commit/351fb5fd67183b8b1a3247e99cf58875885d4b73
