### ISSUE TITLE
Sản Nhi ST-Toa xuất viện đã in vẫn hiển thị toa chưa in nhưng không thấy thuốc

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#37]
BV Sản Nhi ST.
 - Lỗi toa xuất viện đã in nhưng vẫn hiển thị toa chưa in nhưng không hiển thị thuốc (chungtu.dain=1, pshdxn.dain=1)
![ảnh](https://user-images.githubusercontent.com/97272332/174710896-a9d3e05e-81e5-4378-acc1-81ad30c73021.png)
![ảnh](https://user-images.githubusercontent.com/97272332/174710918-8274eb2b-892e-4350-bb29-16f74b29ce4c.png)
![ảnh](https://user-images.githubusercontent.com/97272332/174710947-d509ba72-ace8-4744-a79a-57ed60559153.png)
![ảnh](https://user-images.githubusercontent.com/97272332/174711128-0ab7436e-de54-470b-a69e-15613832905a.png)

Data: tra_sannhist_baocaoclsdichvu
Mabn: 2022027966
Chứng từ: NN1.R22.0620.100049
Ngày chứng từ: 20/06/2022

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0701.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/863831750e4270138c8538736c87cfdcceb9c100)

**Comment by chauthanhtra** [comment]
ok anh @ongtrieuhau
