### ISSUE TITLE
Mở code sử dụng HDDT trên Printer.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#39]
Nhờ a Hậu mở code cho BV Lao Phổi CT - 92016 xài HDDT trên printer dùm em.

**Comment by ongtrieuhau** [comment]
Cập nhật tại đây https://github.com/dh-hos/dhg.hospitalprinter/commit/02467ec07fd2cc3988d4a5b68be9c379dfdd0d97
