### ISSUE TITLE
Hiển thị nhiều số 0 khi lập HDDT cho nhà thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#40]
Khi lập HDDT, Số lượng, Đơn giá, Thành tiền đều hiện nhiều số 0 phía sau. Kiểm nhật ký thì đúng là mình truyền dữ liệu có nhiều số 0.

Data: binh_tamthanct_hddtnhathuoc_000.
BN ngày 23/06.

![image](https://user-images.githubusercontent.com/99630883/175202920-9ae5ec20-783e-4576-8fae-ec6e46055449.png)

**Comment by ongtrieuhau** [comment]
Phần này yêu cầu bên hóa đơn điện thử format lại trang in đi. Code mình đưa trước giờ vẫn vậy, mà mấy chỗ khác đâu bị đâu. @lqbinh1987
