### ISSUE TITLE
Lỗi: in bảng kê đối tượng miễn phí

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#41]
khi in bảng kê đối tượng miễn phí báo lỗi
tên data: an_caolanh_inbangke

khi in báo lỗi:
![image](https://user-images.githubusercontent.com/96155021/175249630-dd131ca0-de06-4fa6-91c1-2293c6b1b400.png)

in ở chức năng này thì không báo lỗi
![image](https://user-images.githubusercontent.com/96155021/175250058-af0b3115-e67b-4f38-91c6-ae84121c3c5c.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0630.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/800a7a154346c17fc459a987b371a31d64d5614c)
