### ISSUE TITLE
Lỗi - Lập phiếu thu ở 2 máy cùng lúc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#42]
Khi 2 máy đồng thời bấm Lập phiếu thu tren cùng 1 BN ở form Hóa đơn điện tử(Hình 1), thì phần mềm sẽ ghi nhận thành 2 phiếu thu khác nhau luôn(Hình 2), và đồng bộ thành 2 Hóa điện tử lun(cấu hình Lập hóa đơn khi lưu phiêu thu).
Data: binh_nhidong_full, ID 2206000044, ngày chứng từ toa thuốc 01/06, 
Hình 1:
![image](https://user-images.githubusercontent.com/99630883/176863462-9e4c6b47-7e90-4996-a855-14528ccdfce8.png)
Hình 2
![image](https://user-images.githubusercontent.com/99630883/176863702-831b02de-0161-42d6-b5d0-63ecc542f3cc.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0704.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/170586f082f5ac9e03c6a72e1040712d8129cfde)
