### ISSUE TITLE
Lỗi - Hiển thị thông báo trống - chức năng in phiếu KCB

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#43]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_test_xml`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [``](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000005` - _**MaKB**_: `2205003359` - _**MaBA**_: `` _**NgayKCB**_: `28/06/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi in phiếu phần mềm báo giờ kết quả thực hiện cls lớn hơn giờ kết thúc - > chọn bỏ qua.
Printer sẽ hiển thị 3 thông báo trống như hình sau:
```
cảnh báo khi in phiếu!
![image](https://user-images.githubusercontent.com/96155021/177260921-0eea2b82-2776-4a27-90a6-60b707f2207f.png)
chọn đồng ý -> bỏ qua
Printer sẽ hiển thị 3 thông báo trống
![image](https://user-images.githubusercontent.com/96155021/177261015-3ef6104e-aa81-4571-819c-cffc0f460e51.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0705.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/cc641e168700d6280621adb537eb0bda7dd8c90a)

**Comment by ongtrieuhau** [comment]
Cập nhật thêm [v3.22.0706.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/8f948865a7c617440d9486c040b9c0c12abef569)

**Comment by le-an-87** [comment]
Đã fix!
