### ISSUE TITLE
Lỗi - Printer in bảng kê bị treo thông báo đang xử lý in ấn

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#46]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **08/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hồng Ngự**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_hongngu_printer`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020045494` - _**MaKB**_: `2207003768` - _**MaBA**_: `N2022004114` _**NgayKCB**_: `08/07/2022` - _**MaPhong**_: `NH01` - _**MaDV**_: `08` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` 

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi in Bảng kê 6556 tại form In phiếu KCB bị treo thông báo (Đang xử lý in ấn)  không in và thoát được!
```
Printer chạy hoài không in và thoát được!
![image](https://user-images.githubusercontent.com/96155021/177906076-dcc30263-c4a8-45dc-927b-442ac4407621.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0708.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/8cf9823ab152c39650b7d5204f8824cdbb93239b)

**Comment by le-an-87** [comment]
Đã fix!
