### ISSUE TITLE
Lỗi - Không lấy thuốc đối với toa đã lập phiếu thu.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#49]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **13/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong_full_2`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2020074041` - _**MaKB**_: `2207000009` - _**MaBA**_: `MaBA` _**NgayKCB**_: `01/07/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `13` - _**MaHH**_: `MaHH` - _**SoHD**_: `DV8.00001/202207` - _**NgayHD**_: `01/07/2022` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN đã in phiếu trừ kho rồi, lập phiếu thu ở form Hóa đơn điện tử rồi luôn, sau đó mở khóa BN đó ra bấm không lấy thuốc vẫn được.
Yêu cầu thêm option cảnh báo và chặn **không cho mở khóa khi đã lập phiếu thu**, và thêm option **chặn không cho bấm Không lấy thuốc khi đã lập phiếu thu**.

![image](https://user-images.githubusercontent.com/99630883/178640391-a91e8492-dc3d-48cc-92b0-b7f5bc0927dc.png)

**Comment by ongtrieuhau** [comment]
Đề nghị kiểm tra lại chức năng năng theo hình sau, và tham số **kolaythuocdathu** : (**Cho phép không lấy thuốc bệnh nhân BHYT đã thu tiền (0 : Không cho phép; 1 : Cho phép)**)
![image](https://user-images.githubusercontent.com/58720300/179666844-23c2043e-6965-4b74-a099-75870f1cdffc.png)
