### ISSUE TITLE
Lỗi - Bảng kê 6556 lấy ICD YHCT phòng 2 ghép vào ICD chính phòng 1 (phòng 1 không có ICD YHCT)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#50]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **Ông Triệu Hậu**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PHÒNG KHÁM ĐA KHOA ĐÔNG TÂY**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_chandoanchinhphongdau`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1ccxZyvZAAqYlmFeQbbH1ma2uFug8Ryf8/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018010458` - _**MaKB**_: `2205017039` - _**MaBA**_: `MaBA` _**NgayKCB**_: `21/05/2022` - _**MaPhong**_: `H25` - _**MaDV**_: `K08` - _**ThangKT**_: `05` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Bệnh nhân khám 2 phòng
+ Phòng 1 không có ICD YHCT kèm chẩn đoán chính ICD10
+ Phòng 2 có ICD YHCT kèm chẩn đoán chính ICD10
- Khi in bảng kê 6556 thì chẩn đoán chính lấy tên ICD YHCT phòng 2 ghép [tên ICD10 phòng 1] 
- Cấu hình 6556 lấy ICD phòng đầu 
![ảnh](https://user-images.githubusercontent.com/97272332/178914756-1fe2314a-aac5-4120-8e40-57b0fd59fd51.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178914960-9616bd9e-191c-4f63-9d8a-a423b935fd1b.png)
![ảnh](https://user-images.githubusercontent.com/97272332/178915149-8d9b742d-6b6e-4979-8cc7-0957cbd4af88.png)

-> PK muốn chỉ lấy ICD của phòng khám đầu tiên làm chẩn đoán chính trên bảng kê 6556

**Comment by ongtrieuhau** [comment]
Hiện tại đang lấy tên bệnh cấu hình có mã YHCT nên lúc nào cũng có. 
![image](https://user-images.githubusercontent.com/58720300/179668256-238d06b8-e4e5-43a3-9a84-8fa39fbb1186.png)

**Comment by chauthanhtra** [comment]
ok anh để em kiểm tra lại

**Comment by chauthanhtra** [comment]
chỉ có 2 lựa chọn thôi hả anh?
1. lấy hết tên ICD YHCT của tất cả các phòng [tên ICD10 phòng khám chính] lên Chẩn đoán chính xác
2. lấy tên ICD10 của phòng khám cấu hình lên Chẩn đoán chính xác

- Không có lựa chọn chỉ lấy tên ICD YHCT phòng cấu hình [tên ICD10 phòng cấu hình]  lên Chẩn đoán chính xác hả anh. vì hiện tại nó ghép sai tên YHCT với tên ICD10 do phòng khám chính nó không có khám YHCT.
-> anh có thể cho thêm 1 lựa chọn chỉ lấy ICD YHCT [ICD10] của 1 phòng khám được cấu hình được không. nếu phòng đó không có ICD YHCT thì chỉ thể hiện ICD10

**Comment by ongtrieuhau** [comment]
Phần có tên YHCT là do sếp @nghivanbi  yêu cầu, miễn có là đưa lên, không phân biệt phòng nên chỗ này sẽ ghép lại.

**Comment by nghivanbi** [comment]
Này có mô tả mà:
[Bi - Mo ta thuoc ho tro benh nhan YHCT_20211201.2.pdf](https://github.com/dh-hos/dhg.hospitalprinter/files/9138851/Bi.-.Mo.ta.thuoc.ho.tro.benh.nhan.YHCT_20211201.2.pdf)

**Comment by nghivanbi** [comment]
Em coi cấu hình theo mô tả, mấy các para đó không sử dụng đại trà cho các bệnh viện @chauthanhtra. Theo chuẩn trước đí.

**Comment by ongtrieuhau** [comment]
> Này có mô tả mà: [Bi - Mo ta thuoc ho tro benh nhan YHCT_20211201.2.pdf](https://github.com/dh-hos/dhg.hospitalprinter/files/9138851/Bi.-.Mo.ta.thuoc.ho.tro.benh.nhan.YHCT_20211201.2.pdf)

Mô tả này hiện chỉ áp dụng cho gửi xml lên cổng, phần phiếu thanh toán 6556 hông có theo cái này.
