### ISSUE TITLE
Lỗi - Không cảnh báo bệnh nhân cùng chi trả

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#51]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/7/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_tamthan_dt_printer`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022002533` - _**MaKB**_: `2207002598` - _**MaBA**_: `` _**NgayKCB**_: `19/07/2022` - _**MaPhong**_: `KB` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Bệnh nhân ngoại trú có phát sinh cùng chi trả nhưng printer không có cảnh báo và vẫn cho in bảng kê 6556.

```
bệnh chưa thu cùng chi trả vẫn cho in bảng kê 6556
![image](https://user-images.githubusercontent.com/96155021/179709568-20e65885-0d93-4369-baaa-6a21f1833897.png)

dm đối tượng đã check kiểm tra cùng chi trả
![image](https://user-images.githubusercontent.com/96155021/179710058-3e338ac1-5735-453a-85ba-167855f92318.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0720.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/f234c20ad5af0bb2c349f9121f5d76ea77651fdd)

**Comment by le-an-87** [comment]
Đã fix!
