### ISSUE TITLE
Lỗi - Xuất bán lẻ kho BHYT.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#52]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `89015`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Tim Mạch AG**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_dbtimmach_072022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `MaBN` - _**MaKB**_: `MaKB` - _**MaBA**_: `MaBA` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `MaHH` - _**SoHD**_: `D56.00001/0722` - _**NgayHD**_: `19/07/2022` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BV sử dụng chức năng xuất bán lẻ của kho BHYT ngoại trú, thu tiền ở viên phí(Không check Viện phí nhà thuốc ở cấu hình máy), nhưng khi thu tiền thì trong bản **thuchi.thucthu_dichvunt** vẫn ghi nhận số tiền.
Đề nghị **không ghi nhận số tiền** vào **thuchi.thucthu_dichvunt** đối với xuất bán lẻ của kho BHYT(kho lẻ thuộc kho chẳn 14, bán thuốc BHYT và KHÔNG BHYT luôn), vì khi đó sẽ ảnh hưởng tiêu chí báo cáo của Nhà thuốc khi báo cáo **Báo cáo/Biên lai/bảng kê biên lai thu.** và **Bảng ngoại trú | nội trú | tổng hợp / Bảng kê thu chi.** của module Fees, vì cái này xuất bán lẻ ở printer xong rồi qua Fees_viện phí(cấu hình máy **không check Viện phí nhà thuốc**) của bệnh viện thu tiền chứ không phải Nhà thuốc thu tiền.

![image](https://user-images.githubusercontent.com/99630883/179715627-eac20657-f47f-47b9-b735-0694bc912de1.png)
![image](https://user-images.githubusercontent.com/99630883/179715737-c12a55c3-d428-42a1-9f39-9b23cb047a4a.png)
![image](https://user-images.githubusercontent.com/99630883/179715777-d0e27faa-218c-498a-9cf0-55685b245945.png)
![image](https://user-images.githubusercontent.com/99630883/179715788-8ff7c041-01a2-4879-984b-9127e06cf93b.png)

**Comment by ongtrieuhau** [comment]
Sai module rồi, kiểm tra lại nhé

**Comment by lqbinh1987** [comment]
Cái này do printer nó ghi nhận số liệu nên fees nó mới lấy lên số liệu sai mà anh.
Với lại hôm qua e có ghi nhận bên module Fees nhưng bản cập nhật của anh Fix Bảng kê biên lai thể hiện âm chi phí viện phí khi có chi phí thuộc nhà thuốc.
Còn cái này là do printer xuất bán lẻ của kho BHYT nhưng khi báo cáo check nhà thuốc nó vẫn lấy lên.

**Comment by ongtrieuhau** [comment]
Cụ thể, xác định, nếu Fees thu tiền chi phí không thuộc chi phí nhà thuốc, mà lên vẫn có số tiền nhà thuốc, thì là do Fees sai. Còn việc xác định nguyên nhân thì phần code sẽ chịu trách nhiệm nó. Module nào đang sai thì ghi nhận module đó.
