### ISSUE TITLE
Lỗi - Không có chi phí phát sinh vẫn cản báo.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#53]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **khach_hang**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12_koinphieuduoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057611` - _**MaKB**_: `2207022577` - _**MaBA**_: `MaBA` _**NgayKCB**_: `21/07/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `01` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN BHYT khám nhưng chi phí chưa vượt ngưỡng thanh toán, không có phát sinh chi phí phải đóng mà printer vẫn hiện cửa sổ cảnh báo không có số tiền, đóng cảnh báo vẫn in được.
Ghi chú: Chỉ bị những BN có nhập mã hộ nghèo và mã chữ cái của thẻ có cấu hình **Ngân sách hỗ trợ chi phí KCB** trong Admin

![image](https://user-images.githubusercontent.com/99630883/180343813-5e54b48a-5ce9-4d7c-84a7-dbb12531f072.png)
![image](https://user-images.githubusercontent.com/99630883/180343827-094213db-ff43-4597-a27d-44ca554f11ef.png)
![image](https://user-images.githubusercontent.com/99630883/180346395-3fc2c801-c8d8-4e38-9b1c-84be07512205.png)
![image](https://user-images.githubusercontent.com/99630883/180346804-3c94ff0a-94a2-474c-8f2e-9646f8071d0d.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [v3.22.0722.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/ba87e321d851089fff7f67673149d14d0ae69e02)
