### ISSUE TITLE
Yêu cầu - Hiển thị LCD nhiều quầy phát thuốc

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalprinter#54]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN QUẬN GÒ VẤP**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbgovap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
- Thực hiện hiển thị LCD phát thuốc mỗi phân khu có thể phát nhiều quầy.
- Bố cục LCD quầy phát thuốc gồm: danh sách bệnh nhân phục vụ, danh sách bệnh nhân chờ chung của phân khu. Tương tự hình:
![image](https://user-images.githubusercontent.com/91751241/180901659-38a87e80-88af-478d-894c-33c151d51a9d.png)

```

**Comment by nghivanbi** [comment]
Đã thống nhất với bệnh viện thực hiện như sau:
- Khi đăng nhập lần đầu in phiếu 01 Printer cho cấu hình số quầy phát thực hiện --> cấp số thứ tự cuốn chiếu theo các quầy đã cấu hình, bổ sung para in quầy và stt trên phiếu 01. Nếu không cấu hình quầy phát --> mỗi lần in người dùng phải chọn quầy.
- Thực hiệm thao tác mời phát thuốc và xác nhận phát xong hiển thị ra Tivi như hiện tại.

**Comment by ongtrieuhau** [comment]
Cập nhật: 
**PrinterSmartout**
[1.22.0926.1](https://github.com/dh-hos/hospitalprintersmartout/commit/606396f1761d5b62bdc6a3b5b7f481bb8ec1e3ce)
**Printer**: [3.22.0926.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/8ab0bb213cc64dc4af84385917596237a9c8c4e6)

**Comment by hvtuan1987** [comment]
Hiện tại phát sinh lỗi khi chổ In phiếu KCB người dùng check Tất cả sau đó chọn bệnh nhân In phiếu 01/KCB thì tất cả các số thứu tự và Tên Quầy đều bị mất á  !
![image](https://user-images.githubusercontent.com/97272364/195022518-ff91f976-2474-45fe-9091-bcba4bb7006b.png)

**Comment by ongtrieuhau** [comment]
Chưa thấy ghi nhận đầy đủ thông tin dữ liệu để kiểm tra

> Hiện tại phát sinh lỗi khi chổ In phiếu KCB người dùng check Tất cả sau đó chọn bệnh nhân In phiếu 01/KCB thì tất cả các số thứu tự và Tên Quầy đều bị mất á ! ![image](https://user-images.githubusercontent.com/97272364/195022518-ff91f976-2474-45fe-9091-bcba4bb7006b.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.22.1012.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/6964d7353c39f3549a8685a7b776e7e66441330c)

**Comment by hvtuan1987** [comment]
Hiện tại bệnh nhân phát sinh % cùng chi trả Khi bấm In phiếu 01/KCB phần mềm cảnh báo Không cho in phiếu khi chưa đóng tiền nhưng lại hiện tên bệnh nhân ra LCD nên sai ! 

![image](https://user-images.githubusercontent.com/97272364/195287834-dd4e4c5c-4f8c-451b-8b25-aab906246cff.png)

Với lại chổ Hiển thị tên Quầy như hình dưới khi có tên bệnh nhân trên danh sách thì mới load Tên QUầy lên nên sai ! 
Nên hỗ trợ Tên QUẦY hiển thị mặc định khi Show ra LCD
![image](https://user-images.githubusercontent.com/97272364/195288291-53a6cd5c-0bee-41e3-968a-e5d7d6741ab4.png)
Và khi bấm Mời bệnh nhân nhận thuốc BV yêu cầu có tín hiệu nhấp nháy  ngay dòng bệnh nhân đó !

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.22.1013.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/790e199d77deec4238165a3a9e4d71174dfa6ffd)

**Comment by ongtrieuhau** [comment]
Cập nhật SmartOut [1.22.1013.1](https://github.com/dh-hos/hospitalprintersmartout/commit/3039d229bfe5029c10c1a4f8e0a76abd4d18952a)

**Comment by ongtrieuhau** [comment]
`Và khi bấm Mời bệnh nhân nhận thuốc BV yêu cầu có tín hiệu nhấp nháy ngay dòng bệnh nhân đó !`, phần này nếu được thì hỗ trợ tới việc đổi màu những bệnh nhân đó thôi nhé, còn việc nhấp nháy thì khó xử lý lắm, với nháy nháy làm người ta rối, khó nhìn lắm.
