### ISSUE TITLE
Lỗi - Cảnh báo sai chi phí.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#56]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79029`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Q12**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_bvq12_koinphieuduoc`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057616` - _**MaKB**_: `2207022582` - _**MaBA**_: `MaBA` _**NgayKCB**_: `22/07/2022` - _**MaPhong**_: `A1.01` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN có phát sinh đóng tiền nhưng số tiền thông báo sai.(Hình 1-2)
Trường hợp BN là hộ nghèo được ngân sách hỗ trợ cũng bị cảnh báo sai số tiền như vậy.(Hình 3-4)
BV khác cũng bị, không riêng gì BV Q12.

Hình 1
![image](https://user-images.githubusercontent.com/99630883/180390078-cb573ba7-4fc5-4a80-b13b-cb702c8cacae.png)
Hình 2
![image](https://user-images.githubusercontent.com/99630883/180391444-66737158-1717-496f-98e3-83127621be38.png)

Hình 3
![image](https://user-images.githubusercontent.com/99630883/180391257-82e41a37-e3fb-41e3-bb16-706b2aeb8031.png)

Hình 4
![image](https://user-images.githubusercontent.com/99630883/180391952-c4e7f478-070d-4fc9-b10f-058c087cc265.png)

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0926.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/2646dd8e3133e847aaeab3c17d490d8f888bec1f)
