### ISSUE TITLE
Lỗi - In toa thuốc Than báo lỗi - BV YHCT cần thơ

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#58]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92013`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV YHCT Cần Thơ**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_yhct_printer`

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022014998` - _**MaKB**_: `2207002631` - _**NgayKCB**_: `27/07/2022` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `13` - _**KhoLe**_: `02` - _**SoHD**_: `KK0.00222/202207` - _**NgayHD**_: `27/07/2022` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
In toa thuốc than ( toa dược liệu) printer báo lỗi không in được.
```
1. printer báo lỗi khi in toa
![image](https://user-images.githubusercontent.com/96155021/181214355-cf7df70f-a2a1-451d-998e-28148adff838.png)

2. Toa dược liệu xem tại Prescription
![image](https://user-images.githubusercontent.com/96155021/181214291-f369b30b-2664-427c-895d-2b20018e7edb.png)

**Comment by le-an-87** [comment]
chổ này anh kiểm tra lại giùm em nhe! có cần lại dữ liệu thì em xin bệnh viện gửi lại cho nhe anh!

**Comment by ongtrieuhau** [comment]
Cho anh xin lại dữ liệu để test nhé @le-an-87

**Comment by le-an-87** [comment]
em restore lại dữ liệu rồi đó anh!
tên data: an_yhct_printer
![image](https://user-images.githubusercontent.com/96155021/192673525-57933916-65f6-4d36-abcf-251ef3392d19.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0928.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/b41ffd136edd989bca2ba1f1f8dceb4a1989e741)

**Comment by le-an-87** [comment]
đã fix!
