### ISSUE TITLE
Lỗi - Không in được bảng kê nhưng vẫn ghi nhận ngày in phiếu trong psdangky.ngayinphieu

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#59]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_ngaygioinnhohonngaygioketqua`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1IOm-kA00nM9kdl48ahfZFkhrOf7tAXcp/view?usp=sharing)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022004343` - _**MaKB**_: `2207026677` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/07/2022` - _**MaPhong**_: `H16` - _**MaDV**_: `K15` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `02` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- PK Đông Tây báo lỗi bệnh nhân có ngày giờ in phiếu nhỏ hơn ngày giờ thực hiện CLS

-- Qua kiểm tra thì phát hiện trường hợp khi in bảng kê 6556 gặp cảnh báo không cho in bảng kê (như còn CLS chưa thực hiện, ngày in phiếu nhỏ hơn ngày trả kết quả CLS,.. ) thì Printer không in được bảng kê nhưng vẫn ghi nhận ngày giờ hiện tại vào psdangky.ngayinphieu.
-- Khi in được bảng kê thì Printer không cập nhật lại ngày giờ in phiếu mà vẫn giữ ngày giờ cũ
-> Giờ in phiếu có thể nhỏ hơn giờ thực hiện CLS
![ảnh](https://user-images.githubusercontent.com/97272332/181435539-0a3a910b-9529-47ce-92fb-f1dfb4c38f70.png)
![ảnh](https://user-images.githubusercontent.com/97272332/181435702-5714ca69-28dc-427e-bb3e-e86a2364b51f.png)
![ảnh](https://user-images.githubusercontent.com/97272332/181436083-10aaddb3-4b47-4575-97c1-c3dce234210d.png)
![ảnh](https://user-images.githubusercontent.com/97272332/181435862-f5c9d5d4-22a9-4e55-81a2-e7119e39941e.png)
![ảnh](https://user-images.githubusercontent.com/97272332/181435959-de5b6551-68db-478f-b75c-6af1662cc437.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/5e35124e2855de367791db7e0e59d66ac7ac6ae6)

**Comment by chauthanhtra** [comment]
Printer mới in phiếu báo lỗi
![ảnh](https://user-images.githubusercontent.com/97272332/192409315-04509373-1e60-4a3a-963b-b3ad381f22be.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/72d02d794855d1ce2ccb70cd2783ed58bd6ede89)
