### ISSUE TITLE
Lỗi - Module Reports khi chọn xem bảng kê bệnh nhân ngoại trú báo lỗi

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#60]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) ``
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) ****
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `thanhbinh3`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021000254` - _**MaKB**_: `2207010128` - _**MaBA**_: `` _**NgayKCB**_: `28/7/2022` - _**MaPhong**_: `03` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Reports khi lick vào xem bảng kê bệnh ngoại trú báo lỗi

```
![image](https://user-images.githubusercontent.com/96155021/181458060-f417331c-a4f7-4215-9a32-57175224b7e4.png)

**Comment by nvvinh-dh** [comment]
@ongtrieuhau  OTH.XForms.dll anh đang sử dụng phiên bản: 1.22.708.1

**Comment by vinh-dh** [comment]
@le-an-87 thử bản này nhé! [Reports 30/08/2022](http://www.fsend.vn/download/mqZNQRwpACobNJyeXlQnhVunjtyUi9X1)
