### ISSUE TITLE
Yêu cầu - Không kiểm tra ngày kết quả CLS lớn hơn ngày in phiếu ở BANT theo đợt và CLS không thanh BHYT

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#61]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_dongtay_bant`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1oznMl_Sgsh-8JiitQjCiUEmRsrLvhsxg/view?usp=sharing)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- PK Đông Tây yêu cầu không kiểm tra thông báo thời gian trả kết quả CLS lớn hơn thời gian in phiếu đối với 2 trường hợp:
--1: Bệnh nhân BANT thanh toán theo đợt
--2: Không kiểm tra đối với các CLS không thanh BHYT (bệnh nhân BHYT ngoại trú có thực hiện CLS thu phí)

![ảnh](https://user-images.githubusercontent.com/97272332/181466906-f9e9cf09-0753-4d00-83ae-3ade531fedc4.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/72d02d794855d1ce2ccb70cd2783ed58bd6ede89)

**Comment by chauthanhtra** [comment]
Printer mới vẫn còn thông báo thời gian thực hiện lớn hơn thòi gian in phiếu nha anh
![ảnh](https://user-images.githubusercontent.com/97272332/192431774-3633c80f-b1e3-44b8-82e3-0f04c0f23206.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.6](https://github.com/dh-hos/dhg.hospitalprinter/commit/aa3d05e96895670c12471f457e660f8dcf8c5708)
