### ISSUE TITLE
Lỗi - đã thu tiền nhưng vẫn cảnh báo

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#62]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **27/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057823` - _**MaKB**_: `2207013844` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/07/2022` - _**MaPhong**_: `30B` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

1. Chỉ định CLS và Thuốc có phát sinh chi phí phải đóng, khi in phiếu thì cảnh báo tổng số tiền phải đóng bị sai, nếu không có thuốc thì cảnh báo số tiền đúng bình thường, còn có thuốc thì cảnh báo sai.
![image](https://user-images.githubusercontent.com/99630883/181468152-4d9b43ed-1d12-4b4e-88e0-cbdc62b796b1.png)
![image](https://user-images.githubusercontent.com/99630883/181468181-12e6c880-0ecb-4fc0-b414-59c0781d69e5.png)
![image](https://user-images.githubusercontent.com/99630883/181468213-62c48fc6-b724-4975-912b-64303c2521fd.png)

2. BN có phát sinh chi phí, đã thu xong hết, nhưng khi in phiếu vẫn in được nhưng vẫn cảnh báo sai tiền và sai số tiền.
![image](https://user-images.githubusercontent.com/99630883/181473144-52ab8d30-7500-457b-b7b9-73633fc1f812.png)
![image](https://user-images.githubusercontent.com/99630883/181473181-d862e837-f81c-491d-ab6e-127dc0b1ae40.png)

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/72d02d794855d1ce2ccb70cd2783ed58bd6ede89)
