### ISSUE TITLE
Lỗi - Chưa thu tiền phát sinh vẫn in phiếu 01 được.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#63]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/07/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92127`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Hòa Hảo CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_hoahao_full`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022057824` - _**MaKB**_: `2207013845` - _**MaBA**_: `MaBA` _**29/07/2022**_: `NgayKCB` - _**MaPhong**_: `30B` - _**MaDV**_: `10` - _**ThangKT**_: `07` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

BN BHYT đăng ký khám DV, thu tiền chênh lệch của ck rồi-thu lần 1, sau đó vô BS chỉ định thêm cls có phát sinh chi phí phải đóng tiền, ra thu tiền lần 2, vô BS chỉ định thêm thuốc có phát sinh chi phí BHYT lần nữa, lúc này chưa thu tiền nhưng printer vần in được phiếu 01, vẫn có cảnh báo số tiền.

![image](https://user-images.githubusercontent.com/99630883/181664335-306fdf0e-600b-4732-a323-4f5ff9110c60.png)
![image](https://user-images.githubusercontent.com/99630883/181664578-c14e7628-4235-490d-a8d1-8ea2c485b36e.png)

**Comment by lqbinh1987** [comment]
Thực hiện theo quy chế và nội quy mới ngày 25/08/2022.

**Comment by ongtrieuhau** [comment]
Nhờ kiểm tra lại, vì test thấy vẫn không in phiếu 01 được. [Xem tại đây](https://www.youtube.com/watch?v=VeohRCj-mTQ)

**Comment by lqbinh1987** [comment]
Nhờ a @ongtrieuhau coi lại dùm, em test printer bản 3.22.0722.1, em chạy trực tiếp trên máy chủ lun mà cũng in đc lun.
Cũng là BN ngày đó lun.

**Comment by ongtrieuhau** [comment]
Vậy kiểm tra lại dữ liệu xem thế nào, vì dữ liệu hổng giống trong hình nhé. Dữ liệu hiện tại nó thế này, hổng giống những hình ảnh ở trên [Video dữ liệu hiện tại trên server](https://www.youtube.com/watch?v=VeohRCj-mTQ)

**Comment by lqbinh1987** [comment]
Em mới phát hiện là, nếu có thu %BHYT trước đó, mà lần sau BS chỉ định thêm **có phát sinh %BHYT nữa** thì lúc này nó mới xảy ra tình trạng **lỗi vẫn cho in phiếu**. Kiểu như nó hiểu là đã thu %BHYT xong hết rồi nên nó cho in lun.
Còn nếu hiện tại mà có phát sinh %BHYT nhưng trước đó không có thu %BHYT lần nào(chỉ thu phần chênh lệch giữa DV và BHYT) thì printer nó chặn không cho in là đúng.
[Video tại đây](https://www.youtube.com/watch?v=p582RvjO21Y)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/72d02d794855d1ce2ccb70cd2783ed58bd6ede89)
