### ISSUE TITLE
Lỗi - Cảnh báo sai thời gian khám bệnh và ghi nhận sai thời gian in phiếu

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#64]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **25/08/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_123hv_ng`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022005855` - _**MaKB**_: `2208004317` - _**NgayKCB**_: `25/08/2022` - _**MaPhong**_: `P07` - _**MaDV**_: `10` - _**ThangKT**_: `08` - _**NamKT**_: `2022`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Khi cấu hình tham số: số phút in phiếu nhỏ hơn số phút tối thiểu = 5 & chọn cho phép và cảnh báo
thì khi in phiếu sẽ cảnh báo sai và ghi nhận ngày giờ in sai trong trường hợp số phút nhỏ hơn 5 phút mà không tính đến giờ
ví dụ trường hợp này:
ngày giờ đăng ký: 25/08/2022 12:44:05
Thời gian in phiếu thực tế là: 25/08/2022 13:47:25
-> ngày giờ in được ghi nhận là: 25/08/2022 12:49:05 PM
Printer lấy ngày giờ đăng ký + thêm 5 phút để ghi nhận ngày giờ in phiếu.

```
tham số
![image](https://user-images.githubusercontent.com/96155021/186595985-4f6bc77f-13e0-4148-a20b-b818fe70fd34.png)
Cảnh báo khi in phiếu:
![image](https://user-images.githubusercontent.com/96155021/186596092-d0abb258-f91f-4cc0-a3fb-7d4b1816e651.png)
Giờ in phiếu trong psdangky ghi nhận sai so với ngày giờ in hiện tại
![image](https://user-images.githubusercontent.com/96155021/186596263-845da98c-0d38-415d-a9a0-170ac5c83467.png)

**Comment by le-an-87** [comment]
anh kiểm tra lỗi này giùm em nhe!

**Comment by ongtrieuhau** [comment]
Trường hợp này không phải lỗi, vì lúc đó cảnh báo cho người dùng tiếp tục hay không, người dùng chọn Tiếp tục nên in là hợp lý. Còn về thời gian thì sẽ ảnh hưởng số phút tối thiểu so với thời gian đăng ký khám là 5', nên lúc in thì sẽ tự động cộng thêm giờ để hợp lý so với cấu hình.

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.5](https://github.com/dh-hos/dhg.hospitalprinter/commit/e6a9cfb7d05e6e97cbd8743cb6608996c6968971)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0928.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/c5cdf5fc712e2d3381031f84acdffb68f5518380)

**Comment by le-an-87** [comment]
đã fix!
