### ISSUE TITLE
Yêu cầu - Chức năng mở khóa toa nội trú.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#65]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Lâm Quốc Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **ngay_tiep_nhan**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92003`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Nhi Đồng CT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_nhidong3`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Printer có chức năng xuất toa thuốc của nội trú, sau khi in toa thuốc sẽ bị khóa, nhưng không có chức năng mở khóa loại toa này ra để thao tác khi cần xử lý. 
Trong form mở khóa chứng từ thì không load được loại toa ra từ nội trú.(Hình 2)
Trong form Nhập bệnh nhân trả cũng không trả được, dán ID của BN lấy được thông tin hành chánh của BN , nhưng khi enter chọn thuốc thì không có thuốc.(Hình 3)

![image](https://user-images.githubusercontent.com/99630883/189287265-498b9d1c-20dd-42b2-bcda-338be747b266.png)

Hình 2
![image](https://user-images.githubusercontent.com/99630883/189287732-31a4c42d-9283-46c4-ad38-7f7e6f51c740.png)

Hình 3
![image](https://user-images.githubusercontent.com/99630883/189287279-25f4913c-955d-42c1-9d84-802b2987f3ad.png)

**Comment by ongtrieuhau** [comment]
Phần in này là sử dụng dll trong nội trú, nên phần mở khóa thì phải xem nghiệp vụ trong nội trú nhé.

**Comment by vuongdh** [comment]
@lqbinh1987 yêu cầu cụ thể cử topic này là gì?

**Comment by lqbinh1987** [comment]
anh @vuongdh, trong nội trú ra toa thuốc của của nhà thuốc á anh, khi Nhà thuốc xác nhận in toa rồi thì sẻ khóa toa đó lại, nếu dư thì ra thêm toa thì ok, nhưng nếu toa sai là không có chổ mở khóa để chỉnh toa -> không làm được gì luôn. Toàn hỗ trợ chỉnh dữ liệu.
![image](https://user-images.githubusercontent.com/99630883/197130735-1367474d-6042-43e4-b473-ce34bb957cb8.png)

**Comment by vuongdh** [comment]
@lqbinh1987 chức năng này thiết kế với mục đích là người bệnh phải mua đúng số thuốc bs chỉ định, không phải muốn mua thì mua không thì thôi

**Comment by vuongdh** [comment]
@lqbinh1987 với thuốc chưa mua thì bs ra toa có quyền sửa xóa

**Comment by vuongdh** [comment]
@lqbinh1987 qui trình của nội trú là không có mở khóa
