### ISSUE TITLE
Yêu cầu - Tắt cảnh báo bệnh nhân có 2 toa thuốc khi in bảng kê printer

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#66]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `77025`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_dongtay_16092022`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
   > _**MaBN**_: `2022001966` - _**MaKB**_: `2209014027` - _**NgayKCB**_: `15/09/2022` - _**MaPhong**_: `H16` - _**MaDV**_: `K15` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
```
Tắt cảnh báo "BỆNH NHÂN NÀY CÓ 2 TOA THUỐC" khi in bảng kê 01


```
Cảnh báo bệnh nhân có 2 toa
![image](https://user-images.githubusercontent.com/96155021/191637268-9516336c-6622-4373-a70e-e8109508e0dd.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Printer: [3.22.0924.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/3d0c3e1006524bc11db81b3b3734be2d93f46c80)

**Comment by le-an-87** [comment]
Đã cập nhật!
