### ISSUE TITLE
Lỗi - Printer cảnh báo chưa thu tiền bệnh nhân hưởng nguồn khác không in được bảng kê

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#67]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **22/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95004`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung Tâm Y Tế TX Giá Rai**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_giarai_pri_ngonkhac`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022000031` - _**MaKB**_: `2209009319` - _**MaBA**_: `MaBA` _**NgayKCB**_: `21/09/2022` - _**MaPhong**_: `38` - _**MaDV**_: `10` - _**ThangKT**_: `09` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Printer cảnh báo bệnh nhân chưa lập phiếu thu không cho in bảng kê đối với bệnh nhân ARV được hưởng chi phí nguồn khác không có số tiền thu trên Fees 

![ảnh](https://user-images.githubusercontent.com/97272332/191640457-ee8a0e6b-380b-42b4-bf79-804c05c442d7.png)

![ảnh](https://user-images.githubusercontent.com/97272332/191640473-506ed152-1877-4e26-a212-6768f2ae81d5.png)

![ảnh](https://user-images.githubusercontent.com/97272332/191640482-437b1d73-bc75-4de4-bb0b-562731aaf083.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/67bf6bccd4e21df28cc7de74cfe039608117dfae)
