### ISSUE TITLE
Yêu cầu - Không hiển thị CẢNH BÁO khi có CLS phát sinh Thu phí đã thu tiền

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalprinter#68]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **26/09/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `mabvbh`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **PK Đông Tây _ Nhứt**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_dongtay_songaychidinh`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
BN BHYT có chi phí phát sinh (Thu phí) đã đóng tiền lập Phiếu thu thì không cho hiển thị CẢNH BÁO khi in phiếu 01 trên Printer

```
![image](https://user-images.githubusercontent.com/98437757/192222603-694f5b81-31c6-4f39-8410-6b7b97d3a65d.png)

![image](https://user-images.githubusercontent.com/98437757/192222649-6afb4a85-8848-4e69-94f8-8f975e75093f.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.0927.4](https://github.com/dh-hos/dhg.hospitalprinter/commit/a7fed97afd96c4295f07ae19d8f437e172bf1ecb)
