### ISSUE TITLE
Yêu cầu - Hỗ trợ Thông tư 36/2021/TT-BYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#69]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/9/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_lapvo_kqcls`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
1. Trường hợp bệnh nhân có mã bệnh kèm theo thì trường 13 XML sẽ có mã bệnh kèm theo nhưng theo cv thì không có yêu cầu ghép tên bệnh đối với bệnh nhân khám Lao. trong mô tả cũng không có yêu cầu ghép tên chẩn đoán.

```
![image](https://user-images.githubusercontent.com/96155021/192675048-29577da2-a185-42af-92b1-fb17c974dc12.png)

**Comment by ongtrieuhau** [comment]
Cái này module Reports thì chuyển qua đó yêu cầu hỗ trợ nhé @le-an-87 , @nghivanbi . Còn nếu do printer ghi nhận sai thì chỉ rõ chỗ sai giúp mình nhé.

**Comment by le-an-87** [comment]
Trường hợp này thì do printer khi in phiếu ghi nhận vào dữ liệu current.psdangky trường kqcdoan
![image](https://user-images.githubusercontent.com/96155021/192681252-584d2a76-a51e-4f68-b0de-2674815f81d2.png)
mô tả
![image](https://user-images.githubusercontent.com/96155021/192681507-b99e12e0-0f28-40a2-a954-aa5ca59e06ca.png)

thông tin bệnh nhân test
tên csdl: an_lapvo_kqcls
mabn: 2022003750 ; makb = 2209005631; madv: 10; maphong: 01; ngaykcb: 26/9/2022.

**Comment by le-an-87** [comment]
đã cập nhật chẩn đoán đúng theo mô tả!
