### ISSUE TITLE
Lỗi - Printer không load đc danh sách bệnh nhân khi Xem thể hiện !

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#73]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **12/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022048190` - _**MaKB**_: `2205014575` - _**MaBA**_: `MaBA` _**NgayKCB**_: `12/10/2022` - _**MaPhong**_: `101` - _**MaDV**_: `10` - _**ThangKT**_: `05` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Bệnh nhân khi In phiếu 01/KCB không load lên danh sách như hình dưới
![image](https://user-images.githubusercontent.com/97272364/195229784-ab739f05-cadc-4de5-9809-ed1951dd18b2.png)

Và khi bấm vào nút Xem thể hiện thì chưa xem đc như hình dưới 
![image](https://user-images.githubusercontent.com/97272364/195229949-ed724918-3c3e-4fd0-9031-6ce9321bf054.png)

```

**Comment by ongtrieuhau** [comment]
Cập nhật [3.22.1012.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/816eb7e353d417eb6f1a4f57fab5e1b3f9c875f4)

**Comment by ongtrieuhau** [comment]
Cập nhật SmartOut [1.22.1012.1](https://github.com/dh-hos/hospitalprintersmartout/commit/d7fa0e2e122c24af8bffe791baccda78b1afec0f)
