### ISSUE TITLE
Yêu cầu - Mở chức năng cho xuất XML vào thư mục khi in phiếu 01 - SYT Đồng Tháp

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalprinter#77]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87190`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BỆNH VIỆN DA LIỄU ĐỒNG THÁP**

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```


```

**Comment by nghivanbi** [comment]
Tuấn cập nhật cho Da Liễu - ĐT.  OK thì close nha.

**Comment by hvtuan1987** [comment]
HIện tại in phiếu 01/KCB bị lỗi như hình ! 
![image](https://user-images.githubusercontent.com/97272364/196849453-2c227256-6f84-41ef-9660-b5703825944d.png)
Dữ liệu tuan_dbdalieudt
![image](https://user-images.githubusercontent.com/97272364/196849550-11e919af-5b1a-422a-a6bd-c1a25cc24fa4.png)
In kho BHYT và Nhà thuốc đều lỗi !

**Comment by ongtrieuhau** [comment]
![image](https://user-images.githubusercontent.com/58720300/196853339-b04866fa-a5e9-44c5-8333-d39edbdbd07d.png)

- **Thứ nhất, không test bằng module mới trong luồng công việc** 

![image](https://user-images.githubusercontent.com/58720300/196853050-7d6905f4-c7e1-4b6f-8238-571b925df8cc.png)

- **Thứ hai, không test bằng module nhất có trên github.com** 
 
![image](https://user-images.githubusercontent.com/58720300/196853257-9d1aca8f-849d-4a0f-8e54-fa6f3765497c.png)

- **Thứ ba, báo lỗi không đúng trong luồng công việc** 
 
![image](https://user-images.githubusercontent.com/58720300/196853625-d498461a-bfa8-4271-a1d6-42d885810859.png)

- **Thứ tư, không kiểm tra những lỗi này có tạo công việc chưa và có bản mới fix lỗi chưa.** 
 
![image](https://user-images.githubusercontent.com/58720300/196853728-5d8660cd-62b9-4efb-9993-1767c2be05d6.png)


@hvtuan1987 , @nghivanbi

**Comment by hvtuan1987** [comment]
Này cập nhật module mới nhưng Printer vẫn để phiên bản củ á

Vào Th 5, 20 thg 10, 2022 vào lúc 11:05 Ông Triệu Hậu <
***@***.***> đã viết:

**Comment by hvtuan1987** [comment]
Đã in đc ! Phải xóa thư mục và cài lại !
