### ISSUE TITLE
Yêu cầu - From in phiếu KCB hiển thị danh sách bệnh nhân bệnh án ngoại trú đúng theo kho cấu hình

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#78]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Thanh Bình**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) ``
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://drive.google.com/file/d/1ADkGMzyMQF3PFUZ3MToc-V1_GfeuT2f8/view?usp=sharing)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
   > _**MaBN**_: `2020017497` - _**MaKB**_: `2210006952` - _**MaBA**_: `N2022000225` _**NgayKCB**_: `18/10/2022` - _**MaPhong**_: `HIV` - _**MaDV**_: `10` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
> _**KhoChan**_: `14` - _**KhoLe**_: `08` 
```
Form in phiếu KCB: 
 - Bệnh viện sử dụng nhiều kho lẻ để cấp phát cho nhiều đối tượng ngoại trú nhưng hiện tại bệnh án ngoại trú thanh toán theo đợt hiển thị ở tất cả các kho.

-> Bệnh viện đề nghị hiển thị danh sách theo đúng kho cấp phát. để tiện cho việc quản lý của khoa dược

```
Đối tượng 25 cấu hình kho cấp phát kho lẻ 08 (kho chẳn 14) và sử dụng tham số bantsdthuoc = 1: theo đối tượng ngoại trú
![image](https://user-images.githubusercontent.com/96155021/196639256-def756f1-1d35-4f30-b076-20f2a5174c75.png)

một số kho ở bệnh viện đều load chung danh sách bệnh án ngoại trú
kho 01
![image](https://user-images.githubusercontent.com/96155021/196639462-66031d41-4331-4343-87ba-af2cc4180def.png)
kho 03
![image](https://user-images.githubusercontent.com/96155021/196639629-6a3d5820-7a22-4e94-a735-93ffd2ef6804.png)

kho 04
![image](https://user-images.githubusercontent.com/96155021/196639565-dcd871b2-dfa1-4281-90ea-f67b988ef1ff.png)

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.22.1029.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/1912967b88e5c156d90216ec43af88bcf45da2f0)

**Comment by le-an-87** [comment]
đã bổ sung!
