### ISSUE TITLE
Lỗi - Bệnh nhân ưu tiên không hiển thị ra Tivi

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#80]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022048197` - _**MaKB**_: `2205014602` - _**MaBA**_: `MaBA` _**NgayKCB**_: `28/10/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `10` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `04` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Bệnh nhân ưu tiên và trong bảng outtv trường uutien=1 thì không hiển thị lên TV được (Hoặc xem thể hiện)
![image](https://user-images.githubusercontent.com/97272364/198503450-70a4c5bb-2f49-444c-9947-da965871d857.png)
Dữ liệu ghi nhận trong bảng outtv
![image](https://user-images.githubusercontent.com/97272364/198504057-3333b7e5-d19a-497b-b496-cca9d1c5a3fa.png)

```

**Comment by ongtrieuhau** [comment]
Đã xem code lại, qui trình hiện tại là những bệnh nhân ưu tiên sẽ được cấp phát thuốc riêng, cấp phát hông theo thứ tự chung, nên nó sẽ không theo danh sách trên tivi. @hvtuan1987 _hỏi lại xem qui trình trên đó như thế nào để mình thực hiện theo qui trình mà bệnh viện mong muốn nhé._

**Comment by ongtrieuhau** [comment]
Xem option này thế nào nhé @hvtuan1987  
![image](https://user-images.githubusercontent.com/58720300/198520412-a8c59ba1-51e1-4444-8d61-97773ad368ac.png)
