### ISSUE TITLE
Yêu cầu - Hỗ trợ Chọn máy in phiếu STT bằng máy in nhiệt để chờ nhận thuốc

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#81]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **28/10/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Hỗ trợ tùy chọn máy in cho In số thứ tự bằng máy in nhiệt chờ nhận thuốc !
Quy trình của BV hiện tại là khi bấm nút In toa thuốc + Mẫu BHYT thì sẽ in ra stt = máy in nhiệt và bảng kê 01/KCB bằng máy canon2900 ! 

Nên BV yêu cầu hỗ trợ để đáp ứng được công việc !

```

**Comment by ongtrieuhau** [comment]
Cập nhật Printer [3.22.1028.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/57d63d741204345c47102f78bf99573837ec7079)
