### ISSUE TITLE
Yêu cầu - chức năng in toa thuốc + Mẫu BHYT

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalprinter#82]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Ân**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `87010`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Thanh Bình ĐT**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `an_thanhbinh_tonkhot10`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

**Bệnh viện đề nghị trường hợp in không lấy thuốc thì printer in ra bảng kê 6556 để bệnh nhân ký lại.**
```
Dữ liệu tháng 10 năm 2022.

Bệnh viện sử dụng cấu hình sổ bản in phiếu bhyt tại printer = 0

Bệnh viện sử dụng in mẫu 01 tại Prescription.
khi in ở printer chỉ để xác nhận phát thuốc nên số bản in ở Prescription = 1 và printer = 0

Bệnh viện đề nghị trường hợp in không lấy thuốc thì printer in ra bảng kê 6556 để bệnh nhân ký lại.

```
cấu hình sử dụng tại printer
![image](https://user-images.githubusercontent.com/96155021/199881450-e427cd78-4c21-41fd-9cf4-c346debd4165.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.3](https://github.com/dh-hos/dhg.hospitalprinter/commit/eafc2a84eb5e486eb4f2adf74db634c2e7e6b7a6)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Khi bấm in đã hiển thị thông báo và chọn đồng ý in bảng kê
-> phần mềm vẫn không in ra được bảng kê thanh toán cls
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/cd672606-6cb5-4165-93e0-2e1d3ff2ebd6)

Khi mở khóa bệnh nhân không lấy thuốc trường psdangky.dain không set lại
=> khi người dùng muốn chỉnh chỉ định cls thì không chỉnh được. (Prescription báo bệnh nhân đã in bảng kê)
![image](https://github.com/dh-hos/dhg.hospitalprinter/assets/96155021/c2a930e2-8eda-47b8-8111-0da3d03897f7)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0916.2](https://github.com/dh-hos/dhg.hospitalprinter/commit/fca50e70538057233ec1773820ad86dce9379949)

PS: @le-an-87 
`Khi mở khóa bệnh nhân không lấy thuốc trường psdangky.dain không set lại 
=> khi người dùng muốn chỉnh chỉ định cls thì không chỉnh được. (Prescription báo bệnh nhân đã in bảng kê)`

**Hướng xử lý**:  
Hiện tại vì không lấy thuốc nên nó vẫn còn trạng thái khóa này, phải **[Phục Hồi]** trong form in phiếu thì mới chỉnh cls được nhé, đây là qui trình thao tác trước giờ nhé

## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by le-an-87** [comment]
Đã bổ sung tùy chọn cho phép in bảng kê trường hợp in bệnh nhân không lấy thuốc!
