### ISSUE TITLE
Yêu cầu - Sử dụng HDDT cho nhà thuốc.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalprinter#83]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)
 Yêu cầu mở thêm chức năng sử dụng hóa đơn điện tử  cho nhà thuốc tại  Printer cho BV Cái Răng - 92006.

**Comment by nghivanbi** [comment]
cùng mã số thuế không?

**Comment by lqbinh1987** [comment]
Cùng mã số thuế anh @nghivanbi  ơi.

**Comment by nghivanbi** [comment]
Này Hậu mở cho bệnh viện nha!

**Comment by ongtrieuhau** [comment]
Cập nhật [Printer 3.23.0104.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/e0d7ec5a81f08ef5492245652ca611b426f7655d)
