### ISSUE TITLE
Yêu cầu - Hỗ trợ đổi màu bệnh nhân khi bấm vào nút Mời nhận thuốc 

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalprinter#84]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **07/11/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `79035`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Bệnh viện Quận Gò Vấp**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tuan_dbgovap`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

1. Hỗ trợ đổi màu dòng Thông tin bệnh nhân khi bấm vào nút Mời Nhận Thuốc (Khác với màu bệnh nhân đang chờ)
![image](https://user-images.githubusercontent.com/97272364/200224032-a7a01b1d-6c76-455c-a21b-27b21f7fbe31.png)

2. Hỗ trợ Phím nóng khi bấm vào nút Mời nhận Thuốc. 
![image](https://user-images.githubusercontent.com/97272364/200223785-9d6c86cd-9276-4b3c-b6fe-61184d340ea5.png)

**Comment by ongtrieuhau** [comment]
- Cập nhật [3.22.1121.1](https://github.com/dh-hos/dhg.hospitalprinter/commit/ee138bf3ba5815fb0228dd9813f93b073f5a230a) để hỗ trợ phím nóng
- Thay đổi màu làm theo hướng dẫn tại đây nhé [huong-dan-doi-mau-xtra-report](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/MoTaThayDoi/Outtv/huong-dan-doi-mau-xtra-report.md)
