### ISSUE TITLE
Lỗi - BV Cái Răng: Kê toa theo đối tượng, kê toa tổng hợp không hiển thị tuối

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/dhg.hospitalprinter#91]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà **
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **1/12/2022**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Cái Răng**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_cairang_printer_tuoi`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2022010411` - _**MaKB**_: `2212000078` - _**MaBA**_: `N2022001519` _**NgayKCB**_: `1/12/2022` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `MaDV` - _**ThangKT**_: `12` - _**NamKT**_: `2022`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `14` - _**KhoLe**_: `05` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

- Bảng kê trên Printer không hiển thị tuổi bệnh nhân (em test thì thấy là bệnh nhân BANT theo ngày)
        +  Kê toa theo đối tượng không hiển thị tuổi 
![ảnh](https://user-images.githubusercontent.com/97272332/205209050-af626e6a-fccc-48c7-9208-f85e03b376af.png)
        + Kê toa tổng hợp Tab1 không hiển thị tuổi
![ảnh](https://user-images.githubusercontent.com/97272332/205209169-6cac5b4c-2046-473e-9105-1a97d51fd224.png)
- Kê toa tổng hợp Tab2 hiển thị sai số tuổi toa xuất bán lẻ mabn: BLD28.00001/1222, chứng từ: D28.00001/1222
![ảnh](https://user-images.githubusercontent.com/97272332/205210073-dec7bbbd-c766-40c5-878d-b7f26379be01.png)
![ảnh](https://user-images.githubusercontent.com/97272332/205210111-23f3561b-0701-4d25-9d77-ebb410424e21.png)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.4](https://github.com/dh-hos/dhg.hospitalprinter/commit/cddb9613bbf421ed327aa23684391655915d1e31)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
Còn lỗi phần kê toa tổng hợp Tab 2
phần xuất bán lẻ không hiển thị tên bệnh nhân, địa chỉ, hiển thị sai tuổi của bệnh nhân

![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/6ba29660-60ca-4690-a8aa-38eba8a5fa1f)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/f1e3bd0f-81ce-4a6b-a402-8a60b3151d4a)

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.5](https://github.com/dh-hos/dhg.hospitalprinter/issues/91#:~:text=2%20minutes%20ago-,3.23.0913.5,-%E2%80%A6)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by ongtrieuhau** [comment]
Cập nhật [3.23.0913.6](https://github.com/dh-hos/dhg.hospitalprinter/commit/67eaa6a50e7d27ce8c239a3a9ac382ac1dd8e771)
## 

<div align="right">
  
  [![View](https://img.shields.io/badge/-Xem%20chi%20ti%E1%BA%BFt%20c%E1%BA%ADp%20nh%E1%BA%ADt-informational?logo=github)](https://github.com/dh-hos/dhg.hospitalprinter/blob/main/Deploy_Tools/CHANGELOG.md)

</div>

**Comment by chauthanhtra** [comment]
Alo anh
Số tuổi trên báo cáo Kê toa tổng hợp Tab 2 đang lấy sai nha anh. nó không lấy số tuổi theo thời điểm lập đơn thuốc mà lấy theo ngày sinh so với ngày hiện tại nên nó bị tăng số tuổi khi xem

Tab 1 : Lấy tuổi khi lập toa thuốc -> Đúng
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/c7f7db06-3f8f-409f-9a6d-6d4cfce01ded)

Tab 2 : Lấy tuổi theo ngày sinh so với ngày hiện tại -> Sai
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/1611f404-6f6a-4c3b-b980-824dd0c2ce9f)

**Comment by ongtrieuhau** [comment]
Thử giùm anh trường hợp lập phiếu bán lẻ mới, xem có bị hông nhé, do bản cũ hổng có ràng buộc chỗ tuổi và ngày sinh, bản mới có fix cái này rồi. Thử giúp a phần này.

**Comment by chauthanhtra** [comment]
Cũng vậy nha anh
Tab 2 :Toa nào cũng tính lại tuổi theo ngày sinh hết nha anh: toa khám bệnh hay bán lẻ đều vậy


![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/59783dc4-0e25-4c44-99fd-e0cc606f244e)
![ảnh](https://github.com/dh-hos/dhg.hospitalprinter/assets/97272332/a3505db2-d076-4585-bdc0-a3169c882be9)
